# # from reportlab.platypus import SimpleDocTemplate, Paragraph
# # from reportlab.lib import styles

# # doc = SimpleDocTemplate("report.pdf")
# # style = styles.getSampleStyleSheet()["BodyText"]

# # content = [
# #     Paragraph("SnapHomz Market Report", style),
# #     Paragraph("Median Price: $640,000", style),
# #     Paragraph("Days on Market: 21", style)
# # ]

# # doc.build(content)

# # print("PDF created")


# import os
# import requests
# from reportlab.lib.pagesizes import letter
# from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
# from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
# from reportlab.lib import colors

# def download_image(url, filename):
#     """Downloads an image from a URL and saves it locally for the PDF."""
#     try:
#         response = requests.get(url, timeout=5)
#         if response.status_code == 200:
#             with open(filename, 'wb') as f:
#                 f.write(response.content)
#             return filename
#     except Exception as e:
#         print(f"Warning: Could not download image from {url}. Error: {e}")
#     return None

# def generate_snap_report(agent_json, market_data, llm_narrative):
#     """
#     Generates a branded PDF market report.
    
#     Parameters:
#     agent_json (dict): Dictionary containing agent profile and branding assets.
#     market_data (dict): Dictionary containing the numerical market metrics.
#     llm_narrative (str): The text response generated by the LLM.
#     """
#     zip_code = agent_json["zip_codes"][0]
#     filename = f"SnapReport_{zip_code}.pdf"
    
#     # 1. Download images safely
#     logo_file = download_image(agent_json.get("logo_url"), "temp_logo.png")
#     photo_file = download_image(agent_json.get("photo_url"), "temp_photo.png")
    
#     # 2. Setup PDF Document
#     doc = SimpleDocTemplate(filename, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
#     story = []
    
#     styles = getSampleStyleSheet()
#     title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=22, leading=26, textColor=colors.HexColor("#1A365D"))
#     subtitle_style = ParagraphStyle('SubTitle', parent=styles['Heading3'], fontSize=12, leading=16, textColor=colors.HexColor("#4A5568"))
#     body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=11, leading=16, textColor=colors.HexColor("#2D3748"))
#     table_text = ParagraphStyle('TableText', parent=styles['Normal'], fontSize=10, leading=12, textColor=colors.HexColor("#2D3748"))
#     table_header = ParagraphStyle('TableHeader', parent=styles['Normal'], fontSize=10, leading=12, fontName="Helvetica-Bold", textColor=colors.white)

#     # 3. Header Section (Logo and Agent Contact)
#     if logo_file:
#         brand_element = Image(logo_file, width=120, height=40)
#     else:
#         brand_element = Paragraph(f"<b>{agent_json['brokerage']}</b>", title_style)
        
#     if photo_file:
#         agent_pic = Image(photo_file, width=50, height=50)
#     else:
#         agent_pic = Paragraph("", body_style)
        
#     agent_info = Paragraph(
#         f"<b>{agent_json['name']}</b><br/>"
#         f"Phone: {agent_json['phone']}<br/>"
#         f"Email: {agent_json['email']}", 
#         body_style
#     )
    
#     contact_sub_table = Table([[agent_pic, agent_info]], colWidths=[60, 140])
#     contact_sub_table.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'MIDDLE')]))

#     header_table = Table([[brand_element, contact_sub_table]], colWidths=[300, 200])
#     header_table.setStyle(TableStyle([
#         ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
#         ('ALIGN', (1,0), (1,0), 'RIGHT')
#     ]))
#     story.append(header_table)
#     story.append(Spacer(1, 10))
    
#     # Decorative Divider Line
#     divider = Table([[""]], colWidths=[500], rowHeights=[2])
#     divider.setStyle(TableStyle([('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#E2E8F0"))]))
#     story.append(divider)
#     story.append(Spacer(1, 15))
    
#     # 4. Report Headings
#     story.append(Paragraph("SnapReport™ Market Intelligence", title_style))
#     story.append(Paragraph(f"Hyperlocal Update for Zip Code {zip_code} ({market_data['city']})", subtitle_style))
#     story.append(Spacer(1, 15))
    
#     # 5. Narrative Section (Using the passed LLM response)
#     story.append(Paragraph("<b>Local Market Analysis</b>", subtitle_style))
#     story.append(Spacer(1, 6))
#     story.append(Paragraph(llm_narrative, body_style))
#     story.append(Spacer(1, 20))
    
#     # 6. Metrics Table
#     story.append(Paragraph("<b>Core Market Metrics</b>", subtitle_style))
#     story.append(Spacer(1, 6))
    
#     table_data = [
#         [Paragraph("Metric", table_header), Paragraph("Current Value", table_header)],
#         [Paragraph("Median Home Price", table_text), Paragraph(f"${market_data['median_price']:,}", table_text)],
#         [Paragraph("Average Days on Market", table_text), Paragraph(f"{market_data['days_on_market']} Days", table_text)],
#         [Paragraph("List-to-Sale Price Ratio", table_text), Paragraph(f"{market_data['list_to_sale_ratio']}%", table_text)],
#         [Paragraph("New Listings This Month", table_text), Paragraph(str(market_data['new_listings']), table_text)],
#         [Paragraph("Months of Inventory", table_text), Paragraph(f"{market_data['inventory_months']} Months", table_text)],
#     ]
    
#     metrics_table = Table(table_data, colWidths=[250, 250])
#     metrics_table.setStyle(TableStyle([
#         ('BACKGROUND', (0, 0), (1, 0), colors.HexColor("#1A365D")),
#         ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
#         ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
#         ('TOPPADDING', (0, 0), (-1, -1), 6),
#         ('LEFTPADDING', (0, 0), (-1, -1), 10),
#         ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor("#F7FAFC"), colors.white]),
#         ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
#     ]))
#     story.append(metrics_table)
    
#     # 7. Build File
#     doc.build(story)
#     print(f"PDF generated successfully: {filename}")

#     # 8. Clean up temporary files
#     for temp_file in ["temp_logo.png", "temp_photo.png"]:
#         if os.path.exists(temp_file):
#             os.remove(temp_file)

# # --- Example Usage ---
# if __name__ == "__main__":
#     # 1. Dynamic Agent JSON Input
#     sample_agent_json = {
#         "agent_id": "A123",
#         "name": "Salman Khan",
#         "phone": "+1 555 111 2222",
#         "email": "john@agency.com",
#         "photo_url": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhUTEhIVFhUXGBgYFRcXGBcWFxcVGBgXGhcYFRUaHiggGR0lHhgaITEiKSkrLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGy0mHyYvLS0tLS0tNS0rLSsvKy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIANoA6AMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAGAQIDBAUHAAj/xABDEAACAQMCBAQDBwIDBwEJAAABAgMABBESIQUGMUETIlFhMnGBBxQjQpGhsVLwYsHRFSQzQ3KS8eEWNERTc4KDssL/xAAZAQADAQEBAAAAAAAAAAAAAAAAAQIDBAX/xAAqEQACAgEDAwQBBAMAAAAAAAAAAQIRAxIhMQRBURMiYXEygZHB0UKx8P/aAAwDAQACEQMRAD8AJeF8kCGBYnuIPGAywPTJ3ORnJ7fpV3lPlW5tp0d5I5Fy5dlzvqDY0g9MZXb2oH5lsjNxK+Dn4XUKASNjEjDJz/i/aoeF8yxjhU2vU0kemL4t9bSYRs56Fc/9pry3GCltHezPa+CD7QGtbi5na31iYSMrsvwSrpAJ1DbKkY+lb3MkKJwjhkBOkGMSeoB8LJJP/wCSg1omgjeQK0kaBRgbY1jBz7D/ADo1+1Ev/uNui7LAzMOgH/CVQfTo1aKTd+C13BvlUhWMjMcuCg1EYOCNO/YUUcucMkuNU7NpWB18TB8zqjBwD22wPN1IFD8/AYkhI165MZBBwqMcE+UbkqMnT36iuj/ZjbottIocSAthm3Gry75B9ayhpyTslbuzmEUSC5nnAIjUsQG8wIkkLeUDvpwSffFH32fATwXdtIjKsuo6CukeG4K7H1xuR2zXM+JFoLqaESnMcjqcjyjRkgnHyFE32ecyaL5I55WzIAkZbAQk79R1J7fKrSkpav8AqCnqK3MXL8VuNcKaTpDNvnRhgCQO2DRcY4n4I/j/AIqq2o9U1OZBpOB08zDasD7Qb7wLyW3SF9cullcEYKOSxAB6YdXz8qu3TOeXbn8zBl/aWPfb0G/0rLDDIm4y+RxW9ARy1eeAUmRGk0oUlwcEBsdj2HU+lbPFr2K7uvvFtpZI00EZwsso3Ukd9IO3rWXyyB4eN8s+ljjC4Jx177Vv8rcAkvJXhULbiF9Ujr50dh5R4a7YyO+ds43xvUo3PZb8Cfgr8twm3uIZNDMXlRycAlN8NnHQbkfImuiRcO0cbaUZAkthn0LKxGfnjSK59zzay22pYiv4bDLhtJIHmCsh3DdMEbN86PuIcwW1vFbX9xJpPhFFQAl3LgHCKPde+w61pitqvkuAF8D5fGJZJgrq8jtDGw206jl2X82TnHsM96m5ilMj28BKpGCSJCyoFY7bd9l7EYNc7v8Aj8jMxiDRqdsaiWC+hYn+NqyZJC27Ek+rEn9zSj0snNykw9Pezo19N5jHhGwv4c8cuG9BgA5B/wAPQUU30rvwGTVqDB4wS4XJxcR5Jxtvvv71w0SAdMfSibgXPNxbwvbMFmgfOUkySufzRt7EA4Od62jh0cFJUbXCIDoRQ3mJdTgDKkfCxGMHPSt7hsU5BJmYaSSAgWNskDU3lH0+VD/L90GDM0qpGxwCQAFLHY56qw/TeiR+JRxoS05du0ehROcfm1DClT0zjHvXLKXuolrcIuSpXZp5GmZyseAXYEDdjknGewzn0rnHBITJcNDgA6nYvncldyBvg770Z8ntDOvEfBDgSQ4IcKDrKSBtlJ2ya5zwW4MZhcDOnSV09MYwf233rdwekug14RzC33sqwLCRlBUbaQoOCo+u/r9K6A3Egl2LceVVRMKowPMTvt8q47w698K5U6AwaQHWTg7noc9wCNq6Dx7iX3fids7MojlgBfJxjQw3z9Tt3qFDRG47cCoD+fOF20V1OE2cyK2nfH4gV2A9N2JxWNcWxliEZJUodSA7BXxs2PnXQOM8FtLq5NweKxqpOpUXwtYGlRguzHOCGwdIIDY3xVS64TwmQaJOKTMCrDrCNsgtpYQ9dh3rPRLVtJfuS47mjzG8tzwjxMsGBjZhkrsCFlVhn+oNt8qja6MPBIptIYq0TlT3DyKMHPfDfrUnHeZuGpYvbpclzICiYVixfrqYYAAzuTWZxBtfL0wB1FdGD7qYj/Irpq9n4Kq0D95JNcISsapZBgZAuzBjgnyg9CTn2r1V+WblpdcRPm0qwXbHl2Yj0PTrXq55ZZQelbGT22Dq15gs55JJ0sddwV8+dPn0DHfrgD06CmcO5p8SaO3ksIEimcR9jg4JXUmnG++PeqXLHKUkaRym4ihlePKoSclWXbXuOmegHep7PkydJYppLu3IjlSR2BbJVDkgA7ZPvVxeZtNcdwWruYPE0W14jLaBPwJAq9emv4RjuBuPoK0PtNnDXwQZ1LBGBjP5ncnUfTAFVOYLxLjjcDREFfFiTO3m0EliPb/Sl5ujMnFLxsviGOLGg41MI0bR+jE49xUy0pNr4/kppUzPmjhYATocFh5gGPm0jc436CjnkqaOKyd1YafFXcehKgdemxoFjuJJsFAY9PnXuX0nVgqNjnp8iaJ5yzcDmkhQszkOoUZPxAjAHpjpWeBe/wDcjHyC/P1jHDxiXUNpY1mA3wxZdJ27+aNqx42CnxQmWXDgYGpQDnYdulF/2o2bSR8PvV8swUowIIZsqHAGemCG6/1Gs9bi2Fm7yMPGWUOVwAwjxhlyfiG371tle+zHPZhBz48MkVpxJhs0eg4HmzJhl+gIYf8A3VDw+VZuBcQCk4AmOCMFQBqwR64GfrVHgTi/4DcwLktAxaMfm0q3iRg+nTFT8ggvwfiCg9Y5tzvu0Tbn17VbilPV5/out7A7lqMSr4YbB1dPcfDn3o7+ziSRLxw52dQijppKAk/Pff3zQDwbizkJEIVO2dYY4+ZGOuSKOeRZM3CO+syMVyxIwMKVPl6b9c9a5rlHL8WZN+4j+2G1EVwlyy5Bj0rsPNKpOlc+mNz7CuUpFcXsurJY4xk9FUdAPQD0FH3248XMl4lsPhhQE79Xk6n2wABVXk2ALGTjriuvK/TuS7nbhx62Dz8nyY2OT796zpOCzIcFTk9PeusQ9RWibFDuVB+e/wClcy6maO2XTQOHS8OlHVD88HvUL2coGSu3tXc5uHRsN0U/MenSmy8EUpnSuPQVS6uXgzfSx8nFeEcWe2kyVBB+JGGQfQ10NNU7JIn4kYjGkKPgV95FwehyOgqrzry5G0JkRAGj322yvfbvWZyBxpkPgk+XHlJ6qM5I/wDNVKXqR1xW6OXLieNnTvs2tFV58NnWvmUjDIQcYZfcHrXKrSCQKCEJXYalBKZwMkNXU/s5uGN1MHfWxTOrCgYDbDIAycYoD4dzDLHmzSMPJG8kWCvldUZ1wPQjHcVblJRTMmxspCCFsKw8TbA8wYflPqRkH611njVrbLGt/cxa/u8B0q24GcE+U7E9Bv0rmC+EJvCYLq8pZsMFR8HC6SevQa66pxW8t1gjhvGAjnQx5yd222yPnnPtSxTuw7GLy1zRHeozJYRgKwU50bas6dtPtVu35htzdLbC2hWQqxB8uBIozoHl3JAyCKzeY+ELbRxyQM/hvjOTvnGQTjGdvXpQZx+WCRVxnx1YFWCnIC7nU/XGBnPqKj1ZqbjIlS3po6pc20d7DNFLCo0g6SB+YdGU42waHeHoJOD3Y6goxOCOunfHpjTUP2WXk8s92Zn1a8NsfLkjB0jt0qHlOIng98p28swHbH/E3GPnXQt1v4KOf3kn3aRxFKuseX3GThl/SlrH+8GRkMmJGx16EjHcr1r1ZvGlyQ0G/wBrXm/2fKDs9s3b+nwjkeh3oTldi6eG4aMxhZNyQCGBOodzkCjmDmThk1nDbcQW4QwjSCqtllG25XoDjp7UQ8KseEzQCW2sHkjwSgIK6tORsrHvggE05bpSbE33MbkjhEEs1pOB5xlsZGxw2cY7e1VeMPOLu9EURleWZ1jwVUZUBcZYjcAH/to+5f4TZSPHcW8QiaHI0qdgWXzIy9ARmuXc1XMjpOQukLNKwdTq1P4rkdOmc4rllFxik3abJl+IyOOS3VAdvhSYZyQjHSW9UIJ6j3rd4Fxi64bE0avG8EZzpf41UnHk3y2D260PWs8jRLFck5kZfDkAzpxgsjb75G++1F3BOX7WZGub1dccWIkBzqOnbXIwwSd9t8VOPVr0pkwuzM5i5qldNc0g/N93UxNHqO2oKNycDHmbHWhiOyFyPEZ2KDd8IQy++PzDsMCjvi/L3Dru2lnstSvbZPVyp0+YqyuTnIGx+VAfDJ4re4eSdy2tCF0jIUZB0gDpt/FaTi497Y5Jphr9lwiilaJZA6XKE/CUOxIwAcH2q59mtkUbilo4ACOEAHTSyMAf2rB5Pu1IidT54sFgMZC5OD8iK6NYWAj4lPMvw3NvEem2qJmU7+uJFP1rbDbXuLxz1HGOUFyNAUb4wewwO2enQ7Vpct8ReG9U4PhvKoQf49sr9Rk+1DnGbRo5GaSMqNbAf0kByM4U9a2uCWZneOeViBHgxrGGGTkjLZzj4SSfeuZqnqvkcccpzpFL7QrZ/wDa1zkE6pFK/wDSVUD+DRNwe0KRgHOT2rOaU3HF5HkUg6gwBOrCqBpx7bfvWjzDdH4UbR/U3ffoBWuaTm6PSwLTuzWtItwM71rLERXM1lcY8G6JbrhguM7ehzRfwPj8jgJKBq2Bx/Nc8oUdMZ6mbrVKshxgjasvifHkgJDLnHv2xtisyHniJtjbzKM7MVOPoaIRfIpyXDJ+aZgkTj1XFcz5VhLXcUeoL4jlMncAEHqB8q6PxUpcREocgg49sdjXLrVMSltegJkqfffGP77V1dPw0cnV8JnbuQeGTwXLBwhjKsFdMYbB275O2/7UD3izxcUuPCjAbxZsb43Z8h9R2U4YHHfNWeT+cD4sJkbSinRvncL1Orpk5zR3zVy5qle5j3WVFEw6jC/CwHywD8hV5E/TfwcF7HPhxSOKK4W4IabIZXiBJDgHSjZG4Pof5oh53mZ+F2t0g1iF1Ljr5HGCdumM1ncU4WhRJMqFcHp5RuSM5+g3qTlbmOW2L2mhZhhiqucDbGFO2MbjeufC4xvUEZeTa5w4i8djw9kVnJZSyhSWMPgvklfqv60KxxLcKfuxQT6SFjl1RswJ3jBPQ4BABqQ8T4jxa4ZYkVHQEYPwRDO+pj1Jx6b4Hao+FcNnSWcXoaR4NIEeA2S+SJAQMlQAMe5qskXJavASjvYQ/ZbYtBcuhyAYx5SMFWGNSn/Ktjlvg7pZ3cbBdUni4UdhuFzjv8vWsvkJcX2csMxsCuDjY7E570UcCnd3vFLE6HkRF2GFGcYA65z1q8Tk1H9SlwcJ4PGiJNG0K+KEBD5OqMoRqCg43PQ16obOZ1cBZD4xZkZT5mLEbhlO+rIr1Rk1XyRK72CpeVpkn1SWN7IBjZQjxPtvqLecEe3pU7W3E0BEEN7DpA8FAuuNVLZkDZXOo9VxsMH1q/xDna8i1BbtHYHGNCn+Ov8AFVbb7SL8hlZx4itvpjBynpp6hs1vHHBrvsSlFnRuReEy28TeM5dpCHZihRtRG4ZSTv71zGXg3E5LhsRzQxamGlYtS4BO+MblvX3NE3KPH7viJLCbSIz51GFfWeg0EY0461c5y4nfwaDFPs+RpISMhlBJXxG23AJA67VD0NKLvYLjVGFDy5fBRi3k1BlIPkCsAwzlS2QSuR0oglilj4ZcRywiNg5WNWOpXyw0kexz07Vl2PM1xFCbi5mkwVykT4WRmyAuAPy9ckjGKq3XF7m+tzLF1BKtEx2DqcB1Ow049elZ+njhco/QlpW6H/ZxGZIuJWqqIpZFDIuSQFeMqpyd8Zz+1YvCfs84nEctaxSeXSVeaNl7ZJUjc7U+8t75USaNFWVNWsROMhSBnQPzbjOn3NYV5zReeVxcSMD3D4yPlW2KcJxovUmtwn/9juKCQstqqjGEKTRKV+YBGa6PwuRoYLRblRHLq8PTrDblW2DDqMDP0FcWHNVyP/iZwe2WOfqCKu/7VkY5mdpGyNOHy3nQ4aPJwD029RVNRhug2jwGfEuTbkvJohhlDO7gvMUUhmLAEBCwxnse1Qw8AmtEJnMPmIC6CSy41HS7YAbrscVu2XFopYh4WSgCqzM2JCTjGd+p/eh24juPvc0U4UoiBoXUaTJGWIZWGfiQnf6Hoa4pThK0kb9LNeqjJmtmF+jEKD4Dk4wTjUAufeqfE+HmQ4YMRnOxx/FW/FP31NWQfDYH5YONq0YZRqzmiVqj0opNtPyDKcFhGtvCJLKw22xqKnKDohyBuK1eWuHkSb598nUTj3rQuEAOosAOw+f8mrvAoiGJIGcZ36/+pqJScuTVQUTH5nRvHyukAgAFgfqQQOuPXFY1nc3sZZnWMouNIjJ1tnqQCSpwN9LDfpmj+eBC5VgCGGR8+v61XThKA+VSB3GdqcJaVwTKKZgJcao3kx1jYnbAyAc7dqw+GcDjW0aWVPFadW8Jf6cIWBG256dPUUV8xRJFbS4P5cfVvKP5pvBZsK6StGq2zKus7J5ThgvrlQvTvWmqlZhlpRbfZAdwCTwJPNbQakGf958yhjjLBdjq2+mTRlbfan4LBWgMkbb+VvNv18IEAFfmRWZzcsNxE08EZURanlaRWFw2vp4ikeSHC5EmSPkayOCWNvdR/eZFlQqQBh08MgDuz/CoHYdetdkU09R5K2dnQbzi/BeIw+FJL4eoAlcmF1w3cfDnPzzScP4HwlQdN1JJpBYt4gyF64LIo27YoGfhmmSbSypb6Vl8TY9Tj6YGfap+DX6nxFjfyYOQw0hsg6WFKUoTX4l2gxtebIF/C4dDgbuzNkFsH0OWYn1NbP8A7UEhJBa6mbbZt8Yz/TnH8UCcuXv3e0aR0C7oSe75TUq77jbIrFsuY7h5GnVgpbLRZGrTkacqdhjAFL1H22REp+A/4vz48WdNnoYbanP8BV3HfrWJyfPeo73MYV/FYl1c4LDrkHPkPoT16YqhcXzDB80+NPc46fiKc7qc5/yqG74vLL5F0QRqj4CnGnY9e7MSFA9aTySf4hrDS951ETnxbREYZwxbVkgZPRMjFLQfxKzcLD4xKCSPEyY1tE7AZOx7/tXqPV8samihxS0iUOyrnQRkr0zt0HqKzOC23iSzHUygoXXKgO6sVycdsdPrWjKI7dg8SH7vcKNQMbeJFkkFihb8TGRnGMgZG9aXHrdrOISIbUxj/mRqxJ6edo9yB6gE74rKWRaaXfY59W2wvBrMqsiogUudHiY8646YbPlz69axOPSBmjt45JZWEmoxtIzBJF3OrWCSeuDmoeWr6Z7iUowfHxRsgiZ1G+pUJIb5E5p/EOLmO6aeKSIHU+qEwFX8qqpLPjfV1HSpiqnTY4tJ13Kc0js0glEglbSwcy5GgnSRoPXGevapbTiDrbhEOG1EHBxv3YeoNWeEWk10okI8PzEPM0IdD5lyo0nKaVOrzDBK4zR3xLl63jjVfM7YC+IcQ6Mbl2KDqe2x9KrLmjHZjk0c74jzBeQIixzqupCNRQB/EUjUAx+HY7H2rPsfCaJZpyAwLZZviJBOdzuSev1op4zxy4uJGt/DgkCoQDhoWcx4y43yC3bHtWRwPgz3Q8UXgSM4wqsZpEPXDeQAfWqTxqF8fIWqGcE4OL4KIJzmNdcniJpLE/lDD4gB61Yj4JcROyyRodDAoN8MCGGcj57H1FFNpALOQEGSRZCRiJdhK258rMNCN1C58pOASMYjguGnlEiSgmEnS2k7ErgqU9j65wfnXPlz1v2M3k/YwVjXQEkjKaGBVlDlFZW1BGQYO2AQTncmpObeOSz3MMsIZBHERrwcapGzIxBG6HAG/uazbaz4i13LZtOWU6iWJGyOciVskHCg5xntijCWPhlrqMMomfUoyzBljAUK4G+xJy2/rjptWyiq1Lx/spy0boG7u5JmDZYHA2LZy3qPn6e9blpJ5Q3TYbUHcTv9TeMNOlncLpGBhTgHH99aJrG8R0UAjOkEipyRaij2Olna3En4igcl2y3YDfSP8iarcN4sY2OlWwxBw7knf0B2XPoKy0jaRyVQaBnUCcFiT5tJx2rWh4Ujqpa2cgHZkcHp/UAcn9M1KSSOlOUuAj4SJmLs82rD5CFFVo8dUGnqu4361uLNkZFAV7ePZsMmXc5yUJPYAOenbvjqKK+FXfioHxjO5Hb6H0qZJ8lJ9jO5sP4SLnGuWMe3xDrVPmtpoo4YLeNXD6zJEzDVIisvlUsDlmJ69cAVT5vvNU0cOtVGoZZjsoJGWPyznasfj33m7kitIZkZRKuiQhlkL6BGZF2zoK4Pzyem9XBbpHn9VnW8PJa47xyTWLiJtM3kR1gLF4W3VI1bbBA2OrY+naty84XA8SySwgZGHeIhCWAyzmHSIyD6gL1rS45wiK2uh4cZi8SKNZLoq0itLEc5jt0BaRyDu5IAx1JoZ5+spRChUvpOEkZCHi8oO7FVyC2QADgbE70ZG1NQizzncXSCG05VlvVWS2uFRRlW8WPdiNtI0kggfpmqlvyull94muJlkKI3RJAiDbzEDcEdiPnTOWGuJLWGC0vQgg0+KPDUSJLnKxqF+NSTuxPm/UVR55trwJHboJcdjqLa5XLGYzOSMbY0rgjfG2Kp5FehOvP0Vr7FfjN6PvctoJZXjAjUxDAR2QKRh2P5i2QRscitez4XDEWW6kkRcMECPHKVkXB8wRfL3HYE5FZvCrI2/DXbTGzkpayggCSNmZQjayfNgnG2MAe1b1lwdQsTaAiBTEHGCW1SavPnqSwO+erU55Pb7eBOW2xgXN1rd0eK4VZACkssuWKjPmC429MZyK2eX+S2dROJrcGMjwmHitll7zamx17Y6iq3OuLfwlmjZ4hnw5IT+MrHchonwCNuoam8oiW4mnurdisBCxaSpBeVMMXZCdKMDjOCc5+dR6zxr1JcEqTju+Avs+VQHLSSpM8gcys/idx5NHmxgMPbrXqHOO8R4k2svA0iEaVEQ0HSPj1YyzDv9PSvURzxnvFWvsXqfALcu8Ue7uAJF8kMYVMZ0tKx2L56kentW4OJaIWMDGZ5LgxiNo1kA0oxKqvX0bPTBoZ4Q8sMKaW8NpgxTUnwjJViFO5JIO/bNWeU4J4JYJJUEqzPcNG0Y8ym2jIciNRueoHtmlPFbbS44X0DjfAsnJ08D+IrIshXVIoBYLryCNj0znvtVSHhUngOGl8+AuvdizlsaBnfoBR5wm9ub9ohbrGluykTNIS7rlgGUacYkxkY6DrQ7ZcHBeCKaVi7NP4ucpIqxyN4aBgcMG6luu2M4pJ5Yx1Za/khN8soPaWoudPDvEM4VIy3ibNNqBkwSemBpx0Oa0eXuO3ctuyyPGZACI3kVsjzEsGO4Zh9Kn4vwCDLiKECWMLL+GdBZh5kDMBtnHU53ArFsZLOa4ZIYriYkkjS7Y3OrUSpAG+dm2361OtZo3X7opu1ZV5v4RfwtBfzy4lnfCGOMrp0IMEnoGYflxuAT2NN5W4Q8aNO7uGfJVo2AALHYsOhGd8YrsnFhb3Vupuo3KRfi+FuAXCthWcbE41DTnG++a51b2qSqz29t4UbhnUW84fckERtGCAgJ7YwOm1dOaUvTqJTlaMaWz4lcMyzXGYFAMhXSpZCSAMKMknBz8jVk8W+7XkKpjSIpEYEkAFlyuo+2kH9atcE4ffxxzTTyrHE5GYyisWjRj0f8oBJFCfM1tIHLSNEpl1MpVgSqAFSHA7sCP0rGEfUnpdUl28vkei38Gx92vPFS7UxfiSaQ8wyitoyJAADhRgqDg/51mc0XESt4ccwuJGYtPOAEQsTnw4gAMjJJJ+lafNfPEdxbR21vG6KqRqztgZKLghQDnBOdzQQ7DI+Y/kV2YISr3qvH12NVBBLa+eyQ4+GSUNjrhjkfxVe1utPlyPT3I7b+lM5fuQHaBz5JenTaQdD8/T3A9ak41ZMpDD4upPZh/UPT3HalLabT7nYt4po3uHsWGAcYO2+PX9ulasH3xT5CCoHoDv8+tCPB+KqowdiDv79Nv2oo4dzANORseoIOM+m1c0oST2OrHOLXJr3F4TGVnVfMuGQZBbr1B6VQ4fzEsMfhufhyBjv/T/NZ/GuNJ0zk5y3U6m7Y3yPlWMUZUe4kwAoZ0Q7742JHc5xVQhf5CnkrgsyXbNIZZ4g+TkKc4B6KCfygevtRLznc29q9rHIuyRJGHhZfEBOeqdcYxg+5oR5T8C7YrNKY5VUthsmJwN2O26n2rTiDySgtbwgSPEoEgModACgJc+ZSMAnGNvlUzxNT3PGk25PUP5W5pu5uIC3kuSUkWSMawqCPSjNGcjpjHTvk1qcU54WIxR2UcdwJwysnTUxYRxM3o5IJwezDpWPzBw2yDardEiOtkkw7yRMdOdcQkGcZ7e9DPELaMhRHJqOMnygEEdT5enrWmjHOWpoe1ncuHyxQxwW5MMEj41wwsGPjMfMWI32yNz3O1T8WtFt2ikaaMRmUJKJmKoyOO3bWNyK51yjaWli8cjH71KPMjxhfDDMrMpYn8RtI7bY9DXuP3N1xdjAJowq9I2XT5yM4HcNjbJ9q5/ShLI73F7bIOJcfW7t7aLwmQ2zGSd86Q8m4yNt23zv6moeL8XlaCSLJe0lIWUr5ij51oBn4TqRcnoATU3BYgbbBjKPCWV2UFS2CQPEIz+J19jt6VJxDhUhW1ghVdMrFo1B/EaWMFz42fhULq/TNWp++q4EnbBfh/CRLKJHlYIPgwdXQbkF9guc1pcPuXi8RYbglVOdcbFFGTnLLnzZO2cY2rRsLK3fhU7ymLxWKeEmcFXYjSVX0OfljrTbbgeYYfFjfKyNG+kDGgrlSW+gAqnO71fQN+S9xnm6a7ljitXMekqcr+ZyMHWfTrt03r1WeLcmw2siXNpAHj0nxUeUuFbAG5PmwfnkE5GMUtZa8cFpg1RLiuwN3d2ryrBIys4GcBGJRmOyLjJyeprUhjkSD74zlLdZHhMeD4ttGNK+PHgggl2Ctt/zFPTNLy3zfJbS3S+AFEks06bxhxqcko56sMEY37GoLvi8F2JLiWZ1ZwYXOd2BADRrH0I3Xf5V0SSj5Y6aZcsOPyrc4S8hxKA8rQ4OoBcKSCv4c2wDDBHcVlWnFLdM6ZsSIz6NblmWRcsjDPUHJHoc0sSRRfdpYJE8RJB48eAD4TElQ4/MD8J9M1OtvbeKJ4I44ZX1o0Z/EiiZc+dA3ZgNVKTi1bv6CVPkyeG31y8klzDK6uQwuC3mRkb8wB2wNWw7Va5F4rLw5njeHxIZMF5EGXUAY29uhIqKTmGNImQoH1CTAwoUu4wHZVHXOCB6CsOPmK4VdCSFRgAthS5AHTVjb+a0UJy4WxSjKX0dF5z5wU2qWsbgrJIfFZQQvgLggIW+IFyASoxgEe9DHEeYrEoCtrqnwoJBMUeAehI8zem3r1oPeUk5OSfUnJ/U03NarAttXYtYkuS9Jxq4MfgiVhD/APLU4QD0A9KziKdXo8E/xW6ilwaUepknSpWWmP0pjJpCMZJx7+/tRjwW9iu49LkGRRuD1I/rA7j1I3FAV1vp+X/mprW5aN1kQ4KEEH5f6is82JTj8mmPJofwFfEuBjOwDemCAR0xn1+dZkvDJE/IWHtnP/rXUuX7hZD4c9uEkxnBHxD1Ru/XPt3q7dcCIbXHIR7aQa81Z5RdM9B4YvdHLeDqxYaYt9s5B2+rDan863BWJUPxSEZ74RDnGe+Wxv8A4a6UvB41BdwCR30nP84rnHNUD3UrsPKiCNIwR+UvgscdNzn61thyqWRNmWXHphsCFqcHP9j9KK7Dis8vl1MdETaNIGVKKT06knO31HahbTjb9/UetS/emTBU4OfcHA7gjcHPeu6UFNHnSjfIScPtbu6iYPbZW3BYtJiIrlScDOCzEDYAdqbacLYM6rFKurZgQC2kjqpONVJb82XII1yGTcHU27kadIBYdcCtSLjUcmpg+hjuMgsQfXPc1yTjOL42+DOUX2NWPj1paiJVWUiGBlDOoV5ZXIG0Y7jAUE9vlU1xyjMwkv4Hltmchwbt47fSRjCshj/Q5wdqy42aGIX1pNrlVyZjIgaKFiq6catw4GMMfXas3mTmWe6i1ykOQApkw2V6nIGcDVnr02oxxirrkVGnaX0y3wi1BYJBrMoXIeMoWeQZ2YFs7/UYrYsL0mAzwmWR3zGBpAMCSDTrDt5QDp0ZY7auu9Y/BOLTeFHa3Vu0geIG2BGjw1UHw2JOAy4BPvtWVaQNI7qC2mIKZsHzS77nbbSDuQOuPasnHyuCGvIaWEFrw4G4KpK7Q/hp5WCydw2/k7EjHY4pvBOAwSQG/l4nD4S58YRhhGsurIGlyCrZIAGkZ2x1FC3CY4ZZSkJwD+JJIu6xouNbH+APVqKeMcoWztK0S62ZRGEbTEuXQurKTs0gJ1YJHt0o1xSqa2YkttyvxvjEtvOJbWRZoI4wjDIkEgYa5PEA2JTy7g98V6qJgeztfu5gKu4KB9cbEpnLBVQnGepz/lXqzlHFdOK+Polyp1QIwRp4hedGwrZ7FiAMkEnfHp1oyt+ARRks8eiQkEBQhALAYCucYO+5P9JoJidd2VG06exLs59cZ8tbvFr6A2xEr3DMVXww6nSHwN/TGMjr3rfInJpJlzVvYo8Q4lKJWVIVUHAYjRJrCnbzAbH3Uio+O3qw6YIRhtAM0mrW3n3Eat2GnGT1OcVo8I4HEzKC2iMDVI5GljpGcKOwOoD9aD7hgzOR0LNj5ZOP2rXHGMpbdjSG7EDUwHevIa81dRqSGkr2d6aDTGKkhFSNGD7VCwqSNtqQD0GOu/8ANLXhSE0AQSpv7Dp9aYR+9Wx1prximI6RyfzvDN4dveLofyqsv/LZhspbvE52GRkEntXTI/L5Sc/Pr/fvXzLjtXYeQeZGuofDc5miABPdk6K3v6H5V53VdOl74/qd/TZnJ6ZfoFHGpVI0HB2ycE/QYoB48yxxSumP+FJ8R77YIPqDuPcCjiRc514x/Hvmuc/aHOgRY0bIkcZ7eWMZyB6FmH/bXN061ZEjp6io42wEU9Btj3H8HtVcks2/9j0qyxHavRxZBHftXtHjk8Yz/pSLvnH/AJpITtUqLSGi3a8QdVK5JQlS6EnS5X4dQ74zmvXF6RqIGoSDSQRqG/YgenY1Sp8ExHQkEelQ8a5E4ovWtyTaHxJ2LKy+DH4m5XcYCHovyO2PQ1f4Rw64/wB2ceKhO8RI0HKsdSx52O/TNEnLPNtoUdLm0h8dznxAoVZX6fi/0HHcbE+ma25Lq4knjaJwjZQfd2xpIA28PPRsDPXfFcObI4ycUv1ObLKtiHidnCsUr3MiiRgFZlxFJOuCcOo2YjIGrAyR0xWFwbiokijguo2ljUHMafE4CokbPIDkSIudPrRvytPHdO6Jb6VDsbjxUwFkIGI0B3B2LegGPWrXFeMW0JkS1TAUDxJljJQFdmCvjTq3657VEI5K1SIjqqzmXNNmOGXEQjYyx4WQCQASqnTBPY4Pp2r1DnG7n73cCRpU3OMkk6VBwMnqfX616uuKil7uTTTF8hnJYTGFhb26pGrYcnT5gN8KF6/31rPgvpTIsK7JKp1AjUMqCDnsmDjP0og4BwCVZGnd1C+URwxk+EctsSO4x0plpcPJcGdYtEardJKEBbLrsiaOuG0j9f182Mlvw/7JSSBjmK5iSIRRuJGXILKcqh7gEbEn9qDq2uYLa5iC/ek8NpcuE28q5xuo+EegNYRr1sEFGOx0QVI8aeTtTDTlrYoUnf6V5TtTSaXsKBjxXojuRXhTTsc0gJwaRq8prxoAdH2qTFQxn/WpyKYETx537ir/ACpxI2t1FNvpB0yAd432YfTY/SquKbo3pNWqBOnZ1t743IDL8BGRjbb+9q57zxOWuNHaNQg9s+Zv1JFF/IdwHtwD+RiNvTqRXP8AiMviSSSH8zMfpnb9q8/pMenJL4O/qsl418lNI6kFLXq9E88jXZiPXcU+m3I6N6GpBSGI/UH1GPqKik239P4qR+n1pjLn+KAPS7qR7V0afi3iojeEqRxxwzxpHjHgIAGRgu6k4J9dzXOVPl+n70RcEeX7m4gOlxJiTChmdcDAJA1FcZBHtXP1MU4q/JllSa3L78xPeO80sjKjHLRI5TCjZdOkjXgYG/pV6OeBQG8TxCfyAZk2ODq/w49cHqPSqF/wdoQ8pjEkCSeE2jKjplZI3PTuMH2G9VH1OqXcAkeHUIpQQA6uPhbykjJXb3wPWsaUt1wZVe6JOfOERRNFLaxhUIBYxkgK2dwQSSK9Vme9t3jkX70sYUEqWSR/xNhpZVUkE7jpS1rj1VTLi21ugvkjsLoRh7h4Y4ySQv4WZegwVGRp6dR8qh4TxThYvmitbm4zKp8UlsQySJvrLtuDgEZGBvvTr7lvhZQTxyIuoa5ZTO8ryZyWJTONRJz5VG9AdvHaiWW4ZCiIPwogMF1wfMz5yrk6e3Rmz0rjjhjUotuuCYramQc/34mvZSGDKmI1KnKkKMkg99yf0oapzmmV6eOChBRXY3WyodSCvClxVjGMaeajfrTzQA7NIaQGvUgJImpxNRxnepDQMWM71YHSqy1PGdqYDqUUma9QBucrcaFvFcqVclh5CuCAxGkFs7gfKsNtsCpLfiLxCVEwFmTRJnO65yMEHY5+dVw2T2qIwUW35HKTdLwOJp1JS1ZIrLkEe1RQtkCp1qvD0PsT/NAD27/KvCl/0pqUDIyeo9z/AJGt/k/jslnLJJFGHbSCMkqE05DOcdQFYg/OsBuvyq9wOUJOhZ/DU5Vn069KsCN0/MOgI96jIriyZcGx/tR1aWOWNZDKDlWV205yVaNQcY32O+1WOVZ2thNbPh4p4dRBypV1I0SJ77bf9NbPFeAvaILqNvKPKFLBSD1CLG+SOoOMnaqXNqpFaRFnVrwKkIZdlEWS2kKNmJJJ1H9BmuGM7SiuGYQbMjhQR1uLUaSspBjcsF0TIfiOeqnByK9WhylwyOGIzzhT+LGAD0UK+p3377ftSUpZ5Qk1Abk1waB4iDb6EhRctiSUKCx6eUY6AUJ8wKqKNI3dzn10qAN/qentRnxExQwKzTIWDKiRqMuQD5pcdAMeYfOhDnjj4vrgSqipGiKiALpOBk5b1OSf2o6WEpSUnwRhUm7YOk0lIKcRXpHUexS4pBSk0gI3pzGmMd6c5pgIKcDTaUUALmps1AakjO1AEgNSoevzqBTUiHc0DJhS0gpwoEQf8xf79akK4JpjDzrUz9aAG16lNJQAqtUMR3b5mlkbG9RW7UAWQevypiHang7Gq7Hyn9KBiIe9SZNRRVIDQI7zwmwik4RHg+O7AyxhvM4dhjA9QDkVzC9sBGzS3YLuhVHiYAmMFdRPXGr27Vt8g8wTNHBaIw8srAoANTQsrNlXPw6WGK1eYuXkmmWGCJULZmAckGV18snnbzMNwST1zXnS1Qk2+Pg5ns6AjjPEU+7tGspKu6sEB3IAwSe4z3r1XOCRWguJXvtYJZY00DMajIDM7DcBe/tXqtZPT2SbNFHYuX/D1vFVbeSPxIZPhkZU1I/5NRIAbOxUnIx6GgPiGfFfOxDEEDsRsRn0q9YM4/4Shiztk9vKScj+aypT5ifU5/WtsGPRt2KghtPBplOroZYppGNezSMaAI+9OpgO9ONADlrxFIDTqAG06I0jGkFAFgDelB830pKQ/EPlSAsinCmLTqYDW+JfrTz1qInzj2zT9WTtQA80hFeNKKAKt5tio4TUl/0FQwmgC2xwmfU1VnJGB9asS/CB9apznf8AShDJoztT6jTpUgoEXuG8Smt2MlvIY5NJUMuM6TjIBPToN6N+Q+LzPNL4zB9UPhC6c6zC7HWrNqbp5T5Riudg0ZfZzFbySXMNy+YDEHKZ0s7q2QQR0KjPzBrHMvaZ5NlZpcC5JkuGuGilK29vnRqKztcPgFQQuF8Nuv1HuR6inlGzNm9zFFrlEiJ4UOqMSkjdj5mAwAQM/KvVyy1ypxOaWWf+IB8X4fw8JmzM4R0LYbzLnfGSoyDtuDigU0fwSvHbT64mXTG5JJXq5JGwO3XGOtAGOlbdLJy1X5OnEthaXFItOrqND2ajY081G1ADR1p+KYopwoAWlFJS0AIa9Xq9QBNEdqST4h8qbAd6WY7j++9ICypp4NRJTxTAaw8w9wal7/36VEx861I9ADjXhXhXjQBXv/hHzqCHtU9+dh86gtuooGWH3JHoKpNuTVlXyTVVfWgROlSkj0qBXp4NAEi0W3HMEr8Pht1ViAgj8oOnyufM7HdiVCrjoAMbUI6T611H7Opo5+HvbTApplk0TRldUeoIwLjOdOWO52OCO1YdQ6im/JnkdLcD+EKUlUFisyOCodsKTt5NXbUNvrXq2Ty/rnNvFLDcTuVVpZAFgQqdX4UgLN5gME4yc4r1Y/lumYNKW5PzlwC4trIvK6hC48ullYk7Bd9mx1JFc3ajz7QLh3B1uzYZcaiTj9aA2rXpq0bHRiXtPKaeoqMU4Guhmg5sVGsZdlUZJYhRjc5JxsPWnnpU3Cf/AHiH/wCrH/8AsKQnwO4xbeHPKmCNLlcEYO3qOxqmK1+az/vU3/V//K1kCiLuKYou0mLXq9XqYz1er1eoA8p3qSbtURqSToP79KAJ0NPqKOpFoAbIfMvzqd+tV5PiWppKAFXrTs0w9ac1AEF+PKPnVeA1Yvvh+v8ArVWPoaAHxVDIdz86mjqCX4jQBKm9PDAVDHU1v0oAcjiuhfZXwJL771A7MmBG4dQrYJJGgqwI3xn6Vz5K6N9m15Illc6JHX/eIfhYr1XB6HvgfpWWWtO5nk/EPeBcC8/xr91gV0kJiRC7r6OPyDByduleoe+2m4dLZFR2VX0B1UlQwO5DAbHJ33r1Y48UNPBjHGpKz//Z", 
#         "brokerage": "SnapHomz",
#         "logo_url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZQAAAB9CAMAAACyJ2VsAAAAkFBMVEX///8jHyAAAADf398gHB0cFxgGAAD09PQaFRaLiorp6elSUFG0s7PCwcESDA4eGRoOBQiFg4QMAQW6ubqYl5ejoqJFQkNtbGxiYGDLy8ssKCkXERP5+fkzMDHb29vu7u6mpaVGQ0R4dnfJyMisq6tcWloyLzCJiIhOTEx1dHQ9OjuTkpNnZWVeXF3U09QoJCVArH/JAAAMy0lEQVR4nO1ch3biOhCFcaW5gKmml4QW9v//7lkzki0LY0IC4YXonrMbkI0s6WqqBioVDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDY0M49M6PPZG1epoPwjnQ+fZ49EwogWA7bm+mcB3vTbA/nB69qj+MsbzCQR+VYHvQTXS8vIcODWwzxghmAGEs2eP7y8iAq+YEYIHtWeP8M/hNLLLKGEI4tazR/m3UIMLiiunxGD57HH+IYwXV8WEC8tEW5YfQt1yP8dJtWrB9Nmj/RswPqO6MhWmg5YfQB3Mz3OiWfkRON4NckKs1J895pfH/tP2RMA3x88e9ItjF9zKSbUab5496tdGB27npFqF7rPH/cpwbjPyGSvarDwOu9J012W4jWeP/HUx/ZLyQlFZPXvsL4vGzZ6XgL9/9thfFV8XFC0qD0M//jopn7Uq4+mq2Wy2dMbsk3A+Lyim66kEfsYBM6IeANi2nfy/nT/8RNmwRwnizqOf80ispXy9307Wjf3zCnxkF+LjYaewEkTX+jc28oG/ZT/86NIAVu0Bv5qUrZUuGPS6U5Y7ma3e27ZCiw9HloJsKXLlT650XwPVjWj7j9ViBg7xV5OSaS/YyonfOeRkwhvRSqqkXNNfHwXK0Xyse/ACpKSrDPP8hXFD0mv2gLeu1EW2m2W993kfLrMnkNZkPPSM7AVIqfGFKti9u5SVoC/aTiopcdmBPc+pmbBpGo4zG4Zcl5nxI6bC8QKkNMikpHMYrrvrIX+94RrMXdD7+mH7pnoApfGjj3f7ZqoXnQ8iOggfMhnEC5AS4Lp5fL/XEtc1sKHN87+uSRud3NgQAuvcK4PLfZNqNG25zKJPkgmP84x/PykOXzc8sHJE1ZcJJBu0qrDGNxdqXUosfYgEtOe5xolf0HhP/H5SaAY82njLvFdviy17n4WM+HJ7IZVccli/8AtYI6Kt7YMm9AqkDGkGqGAiWRQAvSoWWXoH9qp7KfAv8W9Ns0hTUWBaovW+id9PCrq4fg9f5+JFMuB1EKJw8RysZPZk58HIt/YB/eOHHZD9flJQmXjoCw3zskDSk2xrYPbmLD5JURKo9FB9qU5z87BuTcn2r6NutxthB7PuRxVgEirK0Oj29zFAtfEuCeSYfawboZNoHBom2G+7jAOZlNP7IoZ4G6kVndNoMGpDMDl2pR3jULc4gk7/DeBtOUwvdnbYIIbXOkRnONyryBpJCdDZmucNOQlIYhbsgous/D7BFVKW5FLD4dINCwiCADbJMi+hzVw9P4aGpO1Wi6SZyZtpeeClJQEO+1jASgSMBnmEZgyuoCUj5bQHL/m0aQX5IXQmELCnmaYbwD5dyjp1m7g1nYRJ6vWDSnY6rmgYUEMN780D7uXnIyk2uldRvqIFcLANy8TsVretcBKdTlOcfgkpIltgT5rFHjAGSe6gYniZFxF76bbugyU90oQJ74VcxsRvb0qJtbTuPCUlkmo+4Zg+1NnmakF92PBaqbrYZMtMV3tvNJCsYYT3HgrcHu8HSfnH/qr1LihHzhVSKv/47H0b9uF6eGZGiJTjLLdK7hu/usWNYAYs7483uC6xwklZKzqVs8JJWeVdk1RW6mcZ0tid8StISucgf9BL2NzIasLDjNPjSSGPuKmoL8xPJeoLsgFLV9nyTK+RIiVl/BiPU947snpHUqz+1sLkmDgvAHLQQxyPm8hkfdqkICluSKTEh0Sj+LZ00EB2hEiJ35M/iTWyBQXcs3D4BjDZCQVFzlUrHmdzjEPAXgPR6TRSGth+rIEE7xGkxJjaUo6FyWdN5k3e0ya3vywMLtftK6Qk3eerYRPTAPtuqssox2P5JjTWrdaBH6GZXrZE7pbrFtq+ZOh4ZjsxJtBbT41hFNOymHZGSjWuuhB2Wk2herx37GdB82iP5ifj1P1H2oHIrosP2vv1KblGo/E3Hm8w6aMuW61pJ0OLi439fk9SaBUq/2Svl4iaAerubKqCsVO6puVpYmOfsws4yzaI0fPEm2lzL2fAczDsLWpT00trY/HchzZjetzAcw1pNtqeSyP1uMswpS1umuxNky6mJ20hf890tdAG4iJP/flpw5ZYUUMsp4oPcO9WRcITKbgoa3ndST5Y8MhTjvJV8jNSw1j+hAbYsRLkBC55oiIbmmby9yhY6A1uIHb9duY14QkpRVSCFMgefcQFxCM3TgoPviqpCkAff4QjsbPTzzBIPygkJU2JU+ovaxhDUeA1HpG8j+5WW02kuHRc0shMPdfrmKjiMXs3dUGAbqeKi2ukJOLW3P3Db+Vn1Pg0MSJF0sUUK2Fk0w13m0U7c/1JptH34aS4A+khfL3qKSnSmQ0NlO08MnK541LSD+zuukQegrs+WQPpKSWH0aP94N3v222t3AwG3AS4nBPyuXzuDg0tcE3TF18Q5sHmdVIYxqfm4ehC6vn4mFAjUuTgnvZIv6CH1RkpuaMyWi82GCLFX2TXaBpMRWV3paAaBebrEClWVrdOFFpZxc6wIFmwwS7v+s0QTopY91YP3YkNTdfhiZdAxOTNoxnva9yN4d7I50ghzDoDQYvNVBSSwhOeBNRfZ6Q4q+iIiTSZFDISAkSFV0tfSRUd05QUvgvkqIk6cz8EKdIHZ2pDQQaHnwTe9TtUIr7zhCqYnYZToRx7qTtZUF8/4Qb8FlIS1LmOxOUll1iuHVuckWKsdyOgCDxPikJd2macmTojJQWdZzNf7IFmmjF8ZiNnasM5KTUutHetOkiP6O3j2TUpWX+WKXH2oq7iRlKETUalJSL6DL08Ka1dzN0E31JJ8fK1ShN2l7spWrmMFGIuP9UNSc+XSJlzTm5dg3Jk1SnBIq8VpyO5nAUGuURJy04d3RJSxvVTp3tW5jXmExleI2UWAmacqm4S1O8HlkJKkBdf/CSzJCWkjItE7Oh+mRRhka8Wv90GqWTIglrmQNR3StgXwyG9OmxIifzLpLD8CLTPD04+XLFxS0mZU6ScROWbaDgmI5uTlLz0PkFSeMLibolIgVwdlweN7sqoG6uoB+cFxh5so86qM98FuezRZVIoCQBDtT2MP0MKaWsX+lxdn3lf8S7XK7X1y0lpoybMR3noE5vW7aQYtDXtIl/xW1CK6yzc3QU/LMWv2snWVyLBy6SQm6+sXSXVF9NSUmgXeo1UPM9IoUypgOp9FZNC5aAgh3nca9jcTAr/QrV3/69+nlU83ozLpAjpVk4eK7x5XErKgDEnn+R37Koap8gd0w7I4pRiUqjKDeTTKMrDMl14Gyk8kI97lbvjkaRU3nArqeXGB1w+tjXLSEnXUQDD8hwpsaw31Ii+mJThWWDJB8nijNtIWaASvmNyJcNDSeHZv7gnD1x4kWy9L5NC6y7F7LRiOVJkzvpq7quYFFE2kDluNRQUVIU3kfKBMufHj6hfeygpIvp02yKbWzlt6IEWSv01UrK+x7ShyY5kWWKx8kue8plXrpDC06pp4fRBCjRuIYUCefOOCS8JjyVlxl1n04Z+t7nuLquimJhSRdfUlxnzSZ+qLvke6MsJ9ZW83bTqM2NePT9PuUCKSETAomnMjOaEkiRWWrrzSVL4QawXnYYSVncSm8eSkth64aq5gW0HwnEzuZ9cQgrpIxNqq+Gq2wPT7XFW/i2ES1wLmMvMYqGCk8dLpIgfBsIjS/5jmXyL3ECKOKX1IAfVpfkiLpcOfRblBVZTr+gwO+DpuxJSxDmoRx56POGJAPY1S3FG38wPPn9Gf4GUZJ+o/r749bIvkKIsxZ0yxd/5ajAfSXl+dNxX4lDTg6Uw/GXBYySNzITFWJSGW42smqUrLbAJO2Xl1LXkboExylUdmjDha/m/IaXyfVKuKdJpH4AOuEwrboMdZkPfBq7rtj+km/dtz/OoHmjNY1gzUVFztkQ2sustMlIqpwllx9g9Yu0MSDp186R4rNfUV4t4Tg0LuezUE6vTbalTkpCCDRkpU2pISMEXKu5GyuDLv2xAsBbXnzFu1TYjG+zqdtfNyVV4ZJBTloeQYY6vnWiPtSJ9vr6zI3vbaEqkJJFH+MaMw0e2cvUN63QgJdPrS9bpUnp0ZzlCI/C2lCKhGd4WZmkhR22gjsJT5RTWCnC3H23+rqW/c9ZaheOM82/xf4kUfP+lAM5x/r+/R95Tq01ugj96wpBVUl4PxrdE5Sk/Jfn6pHxLgUlW8QfxB0hJWPmisbcebFAu4S+QUqk3QC2Xu47Em+zdKYK9FX+ClMTfX1pwI9zd2ZHiT+GPkJLAMW7CM93Jv0PKL4Im5X8ITcr/EA5ZtTtXW2l8DzOE/ll3DQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ2NS/gPUsLKT+AIpaYAAAAASUVORK5CYII=", 
#         "zip_codes": ["90210"]
#     }
    
#     # 2. Market Data Input
#     sample_market_data = {
#         "city": "Beverly Hills",
#         "median_price": 3500000,
#         "days_on_market": 24,
#         "list_to_sale_ratio": 98.5,
#         "new_listings": 12,
#         "inventory_months": 3.2
#     }
    
#     # 3. Direct Narrative Input coming from the Gemini / LLM call
#     sample_llm_response = (
#         "The Beverly Hills housing market remains highly competitive with a strong median price of $3.5M. "
#         "Homes are selling quickly in just 24 days on average, indicating sustained buyer interest. "
#         "With low inventory levels at 3.2 months, it continues to be an opportunistic time for sellers to list their property."
#     )
    
#     # Run the function
#     generate_snap_report(sample_agent_json, sample_market_data, sample_llm_response)

from jinja2 import Template
from xhtml2pdf import pisa
import os

def generate_pdf_with_jinja(agent_json, market_data, llm_narrative):
    zip_code = agent_json["zip_codes"][0]
    filename = f"SnapReport_{zip_code}.pdf"

    # Notice how @bottom-center is completely removed and replaced with @frame
    html_template = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            @page {
                size: letter;
                margin: 0.6in 0.7in 0.8in 0.7in;
                @frame footer_frame {
                    -pdf-frame-content: footer_content;
                    bottom: 0.3in;
                    margin-left: 0.7in;
                    margin-right: 0.7in;
                    height: 0.3in;
                }
            }
            body {
                font-family: Helvetica, Arial, sans-serif;
                color: #334155;
                line-height: 1.6;
                margin: 0;
                padding: 0;
            }
            #footer_content {
                text-align: center;
                font-size: 8pt;
                color: #94A3B8;
            }
            .header-table {
                width: 100%;
                border-collapse: collapse;
                margin-bottom: 20px;
            }
            .logo { max-height: 42px; display: block; }
            .brokerage-text {
                font-size: 24px; font-weight: bold; color: #1E3A8A; margin: 0;
            }
            .agent-info-table { float: right; border-collapse: collapse; }
            .agent-details-cell { text-align: right; padding-right: 14px; vertical-align: middle; }
            .agent-name { font-size: 16px; font-weight: bold; color: #1E3A8A; margin: 0 0 3px 0; }
            .agent-detail { font-size: 11px; color: #64748B; margin: 0; line-height: 1.4; }
            .agent-photo-cell { vertical-align: middle; width: 64px; }
            .profile-pic {
                width: 60px; height: 60px; border: 2px solid #E2E8F0; display: block;
            }
            .divider { width: 100%; height: 1px; background-color: #E2E8F0; margin: 5px 0 25px 0; clear: both; }
            .report-title { font-size: 26px; font-weight: bold; color: #1E3A8A; margin: 0 0 4px 0; }
            .report-subtitle { font-size: 13px; color: #64748B; font-weight: normal; margin: 0 0 24px 0; }
            .narrative-box { background-color: #F8FAFC; border-left: 4px solid #3B82F6; padding: 18px 20px; margin-bottom: 32px; }
            .narrative-label { font-size: 13px; font-weight: bold; color: #2563EB; margin: 0 0 6px 0; text-transform: uppercase; }
            .narrative-text { font-size: 12px; color: #334155; line-height: 1.65; margin: 0; }
            .section-title { font-size: 15px; font-weight: bold; color: #1E3A8A; margin: 0 0 12px 0; text-transform: uppercase; }
            .metrics-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; border: 1px solid #E2E8F0; }
            .metrics-table th { background-color: #1E3A8A; color: #FFFFFF; font-size: 11px; font-weight: bold; padding: 12px 16px; text-align: left; text-transform: uppercase; }
            .metrics-table td { font-size: 13px; padding: 12px 16px; border-bottom: 1px solid #E2E8F0; color: #334155; }
            .metric-value { font-weight: bold; color: #1E3A8A; text-align: right; }
            .row-even { background-color: #F8FAFC; }
            .row-odd  { background-color: #FFFFFF; }
        </style>
    </head>
    <body>
        <div id="footer_content">
            Powered by {{ agent.brokerage }} &bull; Confidential Market Update
        </div>

        <table class="header-table">
            <tr>
                <td style="vertical-align: middle; width: 45%;">
                    {% if agent.logo_url %}
                    <img src="{{ agent.logo_url }}" class="logo">
                    {% else %}
                    <p class="brokerage-text">{{ agent.brokerage }}</p>
                    {% endif %}
                </td>
                <td style="vertical-align: middle; width: 55%;">
                    <table class="agent-info-table">
                        <tr>
                            <td class="agent-details-cell">
                                <p class="agent-name">{{ agent.name }}</p>
                                <p class="agent-detail">{{ agent.phone }}</p>
                                <p class="agent-detail">{{ agent.email }}</p>
                            </td>
                            {% if agent.photo_url %}
                            <td class="agent-photo-cell">
                                <img src="{{ agent.photo_url }}" class="profile-pic">
                            </td>
                            {% endif %}
                        </tr>
                    </table>
                </td>
            </tr>
        </table>

        <div class="divider"></div>

        <p class="report-title">SnapReport&trade; Market Intelligence</p>
        <p class="report-subtitle">Hyperlocal Update for Zip Code {{ agent.zip_codes[0] }} &mdash; {{ market.city }}</p>

        <div class="narrative-box">
            <p class="narrative-label">Local Market Analysis</p>
            <p class="narrative-text">{{ narrative }}</p>
        </div>

        <p class="section-title">Core Market Metrics</p>

        <table class="metrics-table">
            <thead>
                <tr>
                    <th style="width: 60%;">Metric</th>
                    <th style="width: 40%; text-align: right;">Current Value</th>
                </tr>
            </thead>
            <tbody>
                <tr class="row-odd">
                    <td>Median Home Price</td>
                    <td class="metric-value">${{ "{:,}".format(market.median_price) }}</td>
                </tr>
                <tr class="row-even">
                    <td>Average Days on Market</td>
                    <td class="metric-value">{{ market.days_on_market }} Days</td>
                </tr>
                <tr class="row-odd">
                    <td>List-to-Sale Price Ratio</td>
                    <td class="metric-value">{{ market.list_to_sale_ratio }}%</td>
                </tr>
            </tbody>
        </table>
    </body>
    </html>
    """

    template = Template(html_template)
    rendered_html = template.render(
        agent=agent_json,
        market=market_data,
        narrative=llm_narrative
    )

    print(f"Generating PDF structure for {zip_code}...")
    with open(filename, "w+b") as result_file:
        pisa_status = pisa.CreatePDF(rendered_html, dest=result_file)
        
    if pisa_status.err:
        print(f"Error generating PDF: {pisa_status.err}")
    else:
        print(f"Success! Saved as: {filename}")

# --- Test the function ---

# if __name__ == "__main__":
#     sample_agent = {
#         "agent_id": "A123",
#         "name": "Salman Khan",
#         "phone": "+1 555 111 2222",
#         "email": "salman@snaphomz.com",
#         "photo_url": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhUTEhIVFhUXGBgYFRcXGBcWFxcVGBgXGhcYFRUaHiggGR0lHhgaITEiKSkrLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGy0mHyYvLS0tLS0tNS0rLSsvKy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIANoA6AMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAGAQIDBAUHAAj/xABDEAACAQMCBAQDBwIDBwEJAAABAgMABBESIQUGMUETIlFhMnGBBxQjQpGhsVLwYsHRFSQzQ3KS8eEWNERTc4KDssL/xAAZAQADAQEBAAAAAAAAAAAAAAAAAQIDBAX/xAAqEQACAgEDAwQBBAMAAAAAAAAAAQIRAxIhMQRBURMiYXEygZHB0UKx8P/aAAwDAQACEQMRAD8AJeF8kCGBYnuIPGAywPTJ3ORnJ7fpV3lPlW5tp0d5I5Fy5dlzvqDY0g9MZXb2oH5lsjNxK+Dn4XUKASNjEjDJz/i/aoeF8yxjhU2vU0kemL4t9bSYRs56Fc/9pry3GCltHezPa+CD7QGtbi5na31iYSMrsvwSrpAJ1DbKkY+lb3MkKJwjhkBOkGMSeoB8LJJP/wCSg1omgjeQK0kaBRgbY1jBz7D/ADo1+1Ev/uNui7LAzMOgH/CVQfTo1aKTd+C13BvlUhWMjMcuCg1EYOCNO/YUUcucMkuNU7NpWB18TB8zqjBwD22wPN1IFD8/AYkhI165MZBBwqMcE+UbkqMnT36iuj/ZjbottIocSAthm3Gry75B9ayhpyTslbuzmEUSC5nnAIjUsQG8wIkkLeUDvpwSffFH32fATwXdtIjKsuo6CukeG4K7H1xuR2zXM+JFoLqaESnMcjqcjyjRkgnHyFE32ecyaL5I55WzIAkZbAQk79R1J7fKrSkpav8AqCnqK3MXL8VuNcKaTpDNvnRhgCQO2DRcY4n4I/j/AIqq2o9U1OZBpOB08zDasD7Qb7wLyW3SF9cullcEYKOSxAB6YdXz8qu3TOeXbn8zBl/aWPfb0G/0rLDDIm4y+RxW9ARy1eeAUmRGk0oUlwcEBsdj2HU+lbPFr2K7uvvFtpZI00EZwsso3Ukd9IO3rWXyyB4eN8s+ljjC4Jx177Vv8rcAkvJXhULbiF9Ujr50dh5R4a7YyO+ds43xvUo3PZb8Cfgr8twm3uIZNDMXlRycAlN8NnHQbkfImuiRcO0cbaUZAkthn0LKxGfnjSK59zzay22pYiv4bDLhtJIHmCsh3DdMEbN86PuIcwW1vFbX9xJpPhFFQAl3LgHCKPde+w61pitqvkuAF8D5fGJZJgrq8jtDGw206jl2X82TnHsM96m5ilMj28BKpGCSJCyoFY7bd9l7EYNc7v8Aj8jMxiDRqdsaiWC+hYn+NqyZJC27Ek+rEn9zSj0snNykw9Pezo19N5jHhGwv4c8cuG9BgA5B/wAPQUU30rvwGTVqDB4wS4XJxcR5Jxtvvv71w0SAdMfSibgXPNxbwvbMFmgfOUkySufzRt7EA4Od62jh0cFJUbXCIDoRQ3mJdTgDKkfCxGMHPSt7hsU5BJmYaSSAgWNskDU3lH0+VD/L90GDM0qpGxwCQAFLHY56qw/TeiR+JRxoS05du0ehROcfm1DClT0zjHvXLKXuolrcIuSpXZp5GmZyseAXYEDdjknGewzn0rnHBITJcNDgA6nYvncldyBvg770Z8ntDOvEfBDgSQ4IcKDrKSBtlJ2ya5zwW4MZhcDOnSV09MYwf233rdwekug14RzC33sqwLCRlBUbaQoOCo+u/r9K6A3Egl2LceVVRMKowPMTvt8q47w698K5U6AwaQHWTg7noc9wCNq6Dx7iX3fids7MojlgBfJxjQw3z9Tt3qFDRG47cCoD+fOF20V1OE2cyK2nfH4gV2A9N2JxWNcWxliEZJUodSA7BXxs2PnXQOM8FtLq5NweKxqpOpUXwtYGlRguzHOCGwdIIDY3xVS64TwmQaJOKTMCrDrCNsgtpYQ9dh3rPRLVtJfuS47mjzG8tzwjxMsGBjZhkrsCFlVhn+oNt8qja6MPBIptIYq0TlT3DyKMHPfDfrUnHeZuGpYvbpclzICiYVixfrqYYAAzuTWZxBtfL0wB1FdGD7qYj/Irpq9n4Kq0D95JNcISsapZBgZAuzBjgnyg9CTn2r1V+WblpdcRPm0qwXbHl2Yj0PTrXq55ZZQelbGT22Dq15gs55JJ0sddwV8+dPn0DHfrgD06CmcO5p8SaO3ksIEimcR9jg4JXUmnG++PeqXLHKUkaRym4ihlePKoSclWXbXuOmegHep7PkydJYppLu3IjlSR2BbJVDkgA7ZPvVxeZtNcdwWruYPE0W14jLaBPwJAq9emv4RjuBuPoK0PtNnDXwQZ1LBGBjP5ncnUfTAFVOYLxLjjcDREFfFiTO3m0EliPb/Sl5ujMnFLxsviGOLGg41MI0bR+jE49xUy0pNr4/kppUzPmjhYATocFh5gGPm0jc436CjnkqaOKyd1YafFXcehKgdemxoFjuJJsFAY9PnXuX0nVgqNjnp8iaJ5yzcDmkhQszkOoUZPxAjAHpjpWeBe/wDcjHyC/P1jHDxiXUNpY1mA3wxZdJ27+aNqx42CnxQmWXDgYGpQDnYdulF/2o2bSR8PvV8swUowIIZsqHAGemCG6/1Gs9bi2Fm7yMPGWUOVwAwjxhlyfiG371tle+zHPZhBz48MkVpxJhs0eg4HmzJhl+gIYf8A3VDw+VZuBcQCk4AmOCMFQBqwR64GfrVHgTi/4DcwLktAxaMfm0q3iRg+nTFT8ggvwfiCg9Y5tzvu0Tbn17VbilPV5/out7A7lqMSr4YbB1dPcfDn3o7+ziSRLxw52dQijppKAk/Pff3zQDwbizkJEIVO2dYY4+ZGOuSKOeRZM3CO+syMVyxIwMKVPl6b9c9a5rlHL8WZN+4j+2G1EVwlyy5Bj0rsPNKpOlc+mNz7CuUpFcXsurJY4xk9FUdAPQD0FH3248XMl4lsPhhQE79Xk6n2wABVXk2ALGTjriuvK/TuS7nbhx62Dz8nyY2OT796zpOCzIcFTk9PeusQ9RWibFDuVB+e/wClcy6maO2XTQOHS8OlHVD88HvUL2coGSu3tXc5uHRsN0U/MenSmy8EUpnSuPQVS6uXgzfSx8nFeEcWe2kyVBB+JGGQfQ10NNU7JIn4kYjGkKPgV95FwehyOgqrzry5G0JkRAGj322yvfbvWZyBxpkPgk+XHlJ6qM5I/wDNVKXqR1xW6OXLieNnTvs2tFV58NnWvmUjDIQcYZfcHrXKrSCQKCEJXYalBKZwMkNXU/s5uGN1MHfWxTOrCgYDbDIAycYoD4dzDLHmzSMPJG8kWCvldUZ1wPQjHcVblJRTMmxspCCFsKw8TbA8wYflPqRkH611njVrbLGt/cxa/u8B0q24GcE+U7E9Bv0rmC+EJvCYLq8pZsMFR8HC6SevQa66pxW8t1gjhvGAjnQx5yd222yPnnPtSxTuw7GLy1zRHeozJYRgKwU50bas6dtPtVu35htzdLbC2hWQqxB8uBIozoHl3JAyCKzeY+ELbRxyQM/hvjOTvnGQTjGdvXpQZx+WCRVxnx1YFWCnIC7nU/XGBnPqKj1ZqbjIlS3po6pc20d7DNFLCo0g6SB+YdGU42waHeHoJOD3Y6goxOCOunfHpjTUP2WXk8s92Zn1a8NsfLkjB0jt0qHlOIng98p28swHbH/E3GPnXQt1v4KOf3kn3aRxFKuseX3GThl/SlrH+8GRkMmJGx16EjHcr1r1ZvGlyQ0G/wBrXm/2fKDs9s3b+nwjkeh3oTldi6eG4aMxhZNyQCGBOodzkCjmDmThk1nDbcQW4QwjSCqtllG25XoDjp7UQ8KseEzQCW2sHkjwSgIK6tORsrHvggE05bpSbE33MbkjhEEs1pOB5xlsZGxw2cY7e1VeMPOLu9EURleWZ1jwVUZUBcZYjcAH/to+5f4TZSPHcW8QiaHI0qdgWXzIy9ARmuXc1XMjpOQukLNKwdTq1P4rkdOmc4rllFxik3abJl+IyOOS3VAdvhSYZyQjHSW9UIJ6j3rd4Fxi64bE0avG8EZzpf41UnHk3y2D260PWs8jRLFck5kZfDkAzpxgsjb75G++1F3BOX7WZGub1dccWIkBzqOnbXIwwSd9t8VOPVr0pkwuzM5i5qldNc0g/N93UxNHqO2oKNycDHmbHWhiOyFyPEZ2KDd8IQy++PzDsMCjvi/L3Dru2lnstSvbZPVyp0+YqyuTnIGx+VAfDJ4re4eSdy2tCF0jIUZB0gDpt/FaTi497Y5Jphr9lwiilaJZA6XKE/CUOxIwAcH2q59mtkUbilo4ACOEAHTSyMAf2rB5Pu1IidT54sFgMZC5OD8iK6NYWAj4lPMvw3NvEem2qJmU7+uJFP1rbDbXuLxz1HGOUFyNAUb4wewwO2enQ7Vpct8ReG9U4PhvKoQf49sr9Rk+1DnGbRo5GaSMqNbAf0kByM4U9a2uCWZneOeViBHgxrGGGTkjLZzj4SSfeuZqnqvkcccpzpFL7QrZ/wDa1zkE6pFK/wDSVUD+DRNwe0KRgHOT2rOaU3HF5HkUg6gwBOrCqBpx7bfvWjzDdH4UbR/U3ffoBWuaTm6PSwLTuzWtItwM71rLERXM1lcY8G6JbrhguM7ehzRfwPj8jgJKBq2Bx/Nc8oUdMZ6mbrVKshxgjasvifHkgJDLnHv2xtisyHniJtjbzKM7MVOPoaIRfIpyXDJ+aZgkTj1XFcz5VhLXcUeoL4jlMncAEHqB8q6PxUpcREocgg49sdjXLrVMSltegJkqfffGP77V1dPw0cnV8JnbuQeGTwXLBwhjKsFdMYbB275O2/7UD3izxcUuPCjAbxZsb43Z8h9R2U4YHHfNWeT+cD4sJkbSinRvncL1Orpk5zR3zVy5qle5j3WVFEw6jC/CwHywD8hV5E/TfwcF7HPhxSOKK4W4IabIZXiBJDgHSjZG4Pof5oh53mZ+F2t0g1iF1Ljr5HGCdumM1ncU4WhRJMqFcHp5RuSM5+g3qTlbmOW2L2mhZhhiqucDbGFO2MbjeufC4xvUEZeTa5w4i8djw9kVnJZSyhSWMPgvklfqv60KxxLcKfuxQT6SFjl1RswJ3jBPQ4BABqQ8T4jxa4ZYkVHQEYPwRDO+pj1Jx6b4Hao+FcNnSWcXoaR4NIEeA2S+SJAQMlQAMe5qskXJavASjvYQ/ZbYtBcuhyAYx5SMFWGNSn/Ktjlvg7pZ3cbBdUni4UdhuFzjv8vWsvkJcX2csMxsCuDjY7E570UcCnd3vFLE6HkRF2GFGcYA65z1q8Tk1H9SlwcJ4PGiJNG0K+KEBD5OqMoRqCg43PQ16obOZ1cBZD4xZkZT5mLEbhlO+rIr1Rk1XyRK72CpeVpkn1SWN7IBjZQjxPtvqLecEe3pU7W3E0BEEN7DpA8FAuuNVLZkDZXOo9VxsMH1q/xDna8i1BbtHYHGNCn+Ov8AFVbb7SL8hlZx4itvpjBynpp6hs1vHHBrvsSlFnRuReEy28TeM5dpCHZihRtRG4ZSTv71zGXg3E5LhsRzQxamGlYtS4BO+MblvX3NE3KPH7viJLCbSIz51GFfWeg0EY0461c5y4nfwaDFPs+RpISMhlBJXxG23AJA67VD0NKLvYLjVGFDy5fBRi3k1BlIPkCsAwzlS2QSuR0oglilj4ZcRywiNg5WNWOpXyw0kexz07Vl2PM1xFCbi5mkwVykT4WRmyAuAPy9ckjGKq3XF7m+tzLF1BKtEx2DqcB1Ow049elZ+njhco/QlpW6H/ZxGZIuJWqqIpZFDIuSQFeMqpyd8Zz+1YvCfs84nEctaxSeXSVeaNl7ZJUjc7U+8t75USaNFWVNWsROMhSBnQPzbjOn3NYV5zReeVxcSMD3D4yPlW2KcJxovUmtwn/9juKCQstqqjGEKTRKV+YBGa6PwuRoYLRblRHLq8PTrDblW2DDqMDP0FcWHNVyP/iZwe2WOfqCKu/7VkY5mdpGyNOHy3nQ4aPJwD029RVNRhug2jwGfEuTbkvJohhlDO7gvMUUhmLAEBCwxnse1Qw8AmtEJnMPmIC6CSy41HS7YAbrscVu2XFopYh4WSgCqzM2JCTjGd+p/eh24juPvc0U4UoiBoXUaTJGWIZWGfiQnf6Hoa4pThK0kb9LNeqjJmtmF+jEKD4Dk4wTjUAufeqfE+HmQ4YMRnOxx/FW/FP31NWQfDYH5YONq0YZRqzmiVqj0opNtPyDKcFhGtvCJLKw22xqKnKDohyBuK1eWuHkSb598nUTj3rQuEAOosAOw+f8mrvAoiGJIGcZ36/+pqJScuTVQUTH5nRvHyukAgAFgfqQQOuPXFY1nc3sZZnWMouNIjJ1tnqQCSpwN9LDfpmj+eBC5VgCGGR8+v61XThKA+VSB3GdqcJaVwTKKZgJcao3kx1jYnbAyAc7dqw+GcDjW0aWVPFadW8Jf6cIWBG256dPUUV8xRJFbS4P5cfVvKP5pvBZsK6StGq2zKus7J5ThgvrlQvTvWmqlZhlpRbfZAdwCTwJPNbQakGf958yhjjLBdjq2+mTRlbfan4LBWgMkbb+VvNv18IEAFfmRWZzcsNxE08EZURanlaRWFw2vp4ikeSHC5EmSPkayOCWNvdR/eZFlQqQBh08MgDuz/CoHYdetdkU09R5K2dnQbzi/BeIw+FJL4eoAlcmF1w3cfDnPzzScP4HwlQdN1JJpBYt4gyF64LIo27YoGfhmmSbSypb6Vl8TY9Tj6YGfap+DX6nxFjfyYOQw0hsg6WFKUoTX4l2gxtebIF/C4dDgbuzNkFsH0OWYn1NbP8A7UEhJBa6mbbZt8Yz/TnH8UCcuXv3e0aR0C7oSe75TUq77jbIrFsuY7h5GnVgpbLRZGrTkacqdhjAFL1H22REp+A/4vz48WdNnoYbanP8BV3HfrWJyfPeo73MYV/FYl1c4LDrkHPkPoT16YqhcXzDB80+NPc46fiKc7qc5/yqG74vLL5F0QRqj4CnGnY9e7MSFA9aTySf4hrDS951ETnxbREYZwxbVkgZPRMjFLQfxKzcLD4xKCSPEyY1tE7AZOx7/tXqPV8samihxS0iUOyrnQRkr0zt0HqKzOC23iSzHUygoXXKgO6sVycdsdPrWjKI7dg8SH7vcKNQMbeJFkkFihb8TGRnGMgZG9aXHrdrOISIbUxj/mRqxJ6edo9yB6gE74rKWRaaXfY59W2wvBrMqsiogUudHiY8646YbPlz69axOPSBmjt45JZWEmoxtIzBJF3OrWCSeuDmoeWr6Z7iUowfHxRsgiZ1G+pUJIb5E5p/EOLmO6aeKSIHU+qEwFX8qqpLPjfV1HSpiqnTY4tJ13Kc0js0glEglbSwcy5GgnSRoPXGevapbTiDrbhEOG1EHBxv3YeoNWeEWk10okI8PzEPM0IdD5lyo0nKaVOrzDBK4zR3xLl63jjVfM7YC+IcQ6Mbl2KDqe2x9KrLmjHZjk0c74jzBeQIixzqupCNRQB/EUjUAx+HY7H2rPsfCaJZpyAwLZZviJBOdzuSev1op4zxy4uJGt/DgkCoQDhoWcx4y43yC3bHtWRwPgz3Q8UXgSM4wqsZpEPXDeQAfWqTxqF8fIWqGcE4OL4KIJzmNdcniJpLE/lDD4gB61Yj4JcROyyRodDAoN8MCGGcj57H1FFNpALOQEGSRZCRiJdhK258rMNCN1C58pOASMYjguGnlEiSgmEnS2k7ErgqU9j65wfnXPlz1v2M3k/YwVjXQEkjKaGBVlDlFZW1BGQYO2AQTncmpObeOSz3MMsIZBHERrwcapGzIxBG6HAG/uazbaz4i13LZtOWU6iWJGyOciVskHCg5xntijCWPhlrqMMomfUoyzBljAUK4G+xJy2/rjptWyiq1Lx/spy0boG7u5JmDZYHA2LZy3qPn6e9blpJ5Q3TYbUHcTv9TeMNOlncLpGBhTgHH99aJrG8R0UAjOkEipyRaij2Olna3En4igcl2y3YDfSP8iarcN4sY2OlWwxBw7knf0B2XPoKy0jaRyVQaBnUCcFiT5tJx2rWh4Ujqpa2cgHZkcHp/UAcn9M1KSSOlOUuAj4SJmLs82rD5CFFVo8dUGnqu4361uLNkZFAV7ePZsMmXc5yUJPYAOenbvjqKK+FXfioHxjO5Hb6H0qZJ8lJ9jO5sP4SLnGuWMe3xDrVPmtpoo4YLeNXD6zJEzDVIisvlUsDlmJ69cAVT5vvNU0cOtVGoZZjsoJGWPyznasfj33m7kitIZkZRKuiQhlkL6BGZF2zoK4Pzyem9XBbpHn9VnW8PJa47xyTWLiJtM3kR1gLF4W3VI1bbBA2OrY+naty84XA8SySwgZGHeIhCWAyzmHSIyD6gL1rS45wiK2uh4cZi8SKNZLoq0itLEc5jt0BaRyDu5IAx1JoZ5+spRChUvpOEkZCHi8oO7FVyC2QADgbE70ZG1NQizzncXSCG05VlvVWS2uFRRlW8WPdiNtI0kggfpmqlvyull94muJlkKI3RJAiDbzEDcEdiPnTOWGuJLWGC0vQgg0+KPDUSJLnKxqF+NSTuxPm/UVR55trwJHboJcdjqLa5XLGYzOSMbY0rgjfG2Kp5FehOvP0Vr7FfjN6PvctoJZXjAjUxDAR2QKRh2P5i2QRscitez4XDEWW6kkRcMECPHKVkXB8wRfL3HYE5FZvCrI2/DXbTGzkpayggCSNmZQjayfNgnG2MAe1b1lwdQsTaAiBTEHGCW1SavPnqSwO+erU55Pb7eBOW2xgXN1rd0eK4VZACkssuWKjPmC429MZyK2eX+S2dROJrcGMjwmHitll7zamx17Y6iq3OuLfwlmjZ4hnw5IT+MrHchonwCNuoam8oiW4mnurdisBCxaSpBeVMMXZCdKMDjOCc5+dR6zxr1JcEqTju+Avs+VQHLSSpM8gcys/idx5NHmxgMPbrXqHOO8R4k2svA0iEaVEQ0HSPj1YyzDv9PSvURzxnvFWvsXqfALcu8Ue7uAJF8kMYVMZ0tKx2L56kentW4OJaIWMDGZ5LgxiNo1kA0oxKqvX0bPTBoZ4Q8sMKaW8NpgxTUnwjJViFO5JIO/bNWeU4J4JYJJUEqzPcNG0Y8ym2jIciNRueoHtmlPFbbS44X0DjfAsnJ08D+IrIshXVIoBYLryCNj0znvtVSHhUngOGl8+AuvdizlsaBnfoBR5wm9ub9ohbrGluykTNIS7rlgGUacYkxkY6DrQ7ZcHBeCKaVi7NP4ucpIqxyN4aBgcMG6luu2M4pJ5Yx1Za/khN8soPaWoudPDvEM4VIy3ibNNqBkwSemBpx0Oa0eXuO3ctuyyPGZACI3kVsjzEsGO4Zh9Kn4vwCDLiKECWMLL+GdBZh5kDMBtnHU53ArFsZLOa4ZIYriYkkjS7Y3OrUSpAG+dm2361OtZo3X7opu1ZV5v4RfwtBfzy4lnfCGOMrp0IMEnoGYflxuAT2NN5W4Q8aNO7uGfJVo2AALHYsOhGd8YrsnFhb3Vupuo3KRfi+FuAXCthWcbE41DTnG++a51b2qSqz29t4UbhnUW84fckERtGCAgJ7YwOm1dOaUvTqJTlaMaWz4lcMyzXGYFAMhXSpZCSAMKMknBz8jVk8W+7XkKpjSIpEYEkAFlyuo+2kH9atcE4ffxxzTTyrHE5GYyisWjRj0f8oBJFCfM1tIHLSNEpl1MpVgSqAFSHA7sCP0rGEfUnpdUl28vkei38Gx92vPFS7UxfiSaQ8wyitoyJAADhRgqDg/51mc0XESt4ccwuJGYtPOAEQsTnw4gAMjJJJ+lafNfPEdxbR21vG6KqRqztgZKLghQDnBOdzQQ7DI+Y/kV2YISr3qvH12NVBBLa+eyQ4+GSUNjrhjkfxVe1utPlyPT3I7b+lM5fuQHaBz5JenTaQdD8/T3A9ak41ZMpDD4upPZh/UPT3HalLabT7nYt4po3uHsWGAcYO2+PX9ulasH3xT5CCoHoDv8+tCPB+KqowdiDv79Nv2oo4dzANORseoIOM+m1c0oST2OrHOLXJr3F4TGVnVfMuGQZBbr1B6VQ4fzEsMfhufhyBjv/T/NZ/GuNJ0zk5y3U6m7Y3yPlWMUZUe4kwAoZ0Q7742JHc5xVQhf5CnkrgsyXbNIZZ4g+TkKc4B6KCfygevtRLznc29q9rHIuyRJGHhZfEBOeqdcYxg+5oR5T8C7YrNKY5VUthsmJwN2O26n2rTiDySgtbwgSPEoEgModACgJc+ZSMAnGNvlUzxNT3PGk25PUP5W5pu5uIC3kuSUkWSMawqCPSjNGcjpjHTvk1qcU54WIxR2UcdwJwysnTUxYRxM3o5IJwezDpWPzBw2yDardEiOtkkw7yRMdOdcQkGcZ7e9DPELaMhRHJqOMnygEEdT5enrWmjHOWpoe1ncuHyxQxwW5MMEj41wwsGPjMfMWI32yNz3O1T8WtFt2ikaaMRmUJKJmKoyOO3bWNyK51yjaWli8cjH71KPMjxhfDDMrMpYn8RtI7bY9DXuP3N1xdjAJowq9I2XT5yM4HcNjbJ9q5/ShLI73F7bIOJcfW7t7aLwmQ2zGSd86Q8m4yNt23zv6moeL8XlaCSLJe0lIWUr5ij51oBn4TqRcnoATU3BYgbbBjKPCWV2UFS2CQPEIz+J19jt6VJxDhUhW1ghVdMrFo1B/EaWMFz42fhULq/TNWp++q4EnbBfh/CRLKJHlYIPgwdXQbkF9guc1pcPuXi8RYbglVOdcbFFGTnLLnzZO2cY2rRsLK3fhU7ymLxWKeEmcFXYjSVX0OfljrTbbgeYYfFjfKyNG+kDGgrlSW+gAqnO71fQN+S9xnm6a7ljitXMekqcr+ZyMHWfTrt03r1WeLcmw2siXNpAHj0nxUeUuFbAG5PmwfnkE5GMUtZa8cFpg1RLiuwN3d2ryrBIys4GcBGJRmOyLjJyeprUhjkSD74zlLdZHhMeD4ttGNK+PHgggl2Ctt/zFPTNLy3zfJbS3S+AFEks06bxhxqcko56sMEY37GoLvi8F2JLiWZ1ZwYXOd2BADRrH0I3Xf5V0SSj5Y6aZcsOPyrc4S8hxKA8rQ4OoBcKSCv4c2wDDBHcVlWnFLdM6ZsSIz6NblmWRcsjDPUHJHoc0sSRRfdpYJE8RJB48eAD4TElQ4/MD8J9M1OtvbeKJ4I44ZX1o0Z/EiiZc+dA3ZgNVKTi1bv6CVPkyeG31y8klzDK6uQwuC3mRkb8wB2wNWw7Va5F4rLw5njeHxIZMF5EGXUAY29uhIqKTmGNImQoH1CTAwoUu4wHZVHXOCB6CsOPmK4VdCSFRgAthS5AHTVjb+a0UJy4WxSjKX0dF5z5wU2qWsbgrJIfFZQQvgLggIW+IFyASoxgEe9DHEeYrEoCtrqnwoJBMUeAehI8zem3r1oPeUk5OSfUnJ/U03NarAttXYtYkuS9Jxq4MfgiVhD/APLU4QD0A9KziKdXo8E/xW6ilwaUepknSpWWmP0pjJpCMZJx7+/tRjwW9iu49LkGRRuD1I/rA7j1I3FAV1vp+X/mprW5aN1kQ4KEEH5f6is82JTj8mmPJofwFfEuBjOwDemCAR0xn1+dZkvDJE/IWHtnP/rXUuX7hZD4c9uEkxnBHxD1Ru/XPt3q7dcCIbXHIR7aQa81Z5RdM9B4YvdHLeDqxYaYt9s5B2+rDan863BWJUPxSEZ74RDnGe+Wxv8A4a6UvB41BdwCR30nP84rnHNUD3UrsPKiCNIwR+UvgscdNzn61thyqWRNmWXHphsCFqcHP9j9KK7Dis8vl1MdETaNIGVKKT06knO31HahbTjb9/UetS/emTBU4OfcHA7gjcHPeu6UFNHnSjfIScPtbu6iYPbZW3BYtJiIrlScDOCzEDYAdqbacLYM6rFKurZgQC2kjqpONVJb82XII1yGTcHU27kadIBYdcCtSLjUcmpg+hjuMgsQfXPc1yTjOL42+DOUX2NWPj1paiJVWUiGBlDOoV5ZXIG0Y7jAUE9vlU1xyjMwkv4Hltmchwbt47fSRjCshj/Q5wdqy42aGIX1pNrlVyZjIgaKFiq6catw4GMMfXas3mTmWe6i1ykOQApkw2V6nIGcDVnr02oxxirrkVGnaX0y3wi1BYJBrMoXIeMoWeQZ2YFs7/UYrYsL0mAzwmWR3zGBpAMCSDTrDt5QDp0ZY7auu9Y/BOLTeFHa3Vu0geIG2BGjw1UHw2JOAy4BPvtWVaQNI7qC2mIKZsHzS77nbbSDuQOuPasnHyuCGvIaWEFrw4G4KpK7Q/hp5WCydw2/k7EjHY4pvBOAwSQG/l4nD4S58YRhhGsurIGlyCrZIAGkZ2x1FC3CY4ZZSkJwD+JJIu6xouNbH+APVqKeMcoWztK0S62ZRGEbTEuXQurKTs0gJ1YJHt0o1xSqa2YkttyvxvjEtvOJbWRZoI4wjDIkEgYa5PEA2JTy7g98V6qJgeztfu5gKu4KB9cbEpnLBVQnGepz/lXqzlHFdOK+Polyp1QIwRp4hedGwrZ7FiAMkEnfHp1oyt+ARRks8eiQkEBQhALAYCucYO+5P9JoJidd2VG06exLs59cZ8tbvFr6A2xEr3DMVXww6nSHwN/TGMjr3rfInJpJlzVvYo8Q4lKJWVIVUHAYjRJrCnbzAbH3Uio+O3qw6YIRhtAM0mrW3n3Eat2GnGT1OcVo8I4HEzKC2iMDVI5GljpGcKOwOoD9aD7hgzOR0LNj5ZOP2rXHGMpbdjSG7EDUwHevIa81dRqSGkr2d6aDTGKkhFSNGD7VCwqSNtqQD0GOu/8ANLXhSE0AQSpv7Dp9aYR+9Wx1prximI6RyfzvDN4dveLofyqsv/LZhspbvE52GRkEntXTI/L5Sc/Pr/fvXzLjtXYeQeZGuofDc5miABPdk6K3v6H5V53VdOl74/qd/TZnJ6ZfoFHGpVI0HB2ycE/QYoB48yxxSumP+FJ8R77YIPqDuPcCjiRc514x/Hvmuc/aHOgRY0bIkcZ7eWMZyB6FmH/bXN061ZEjp6io42wEU9Btj3H8HtVcks2/9j0qyxHavRxZBHftXtHjk8Yz/pSLvnH/AJpITtUqLSGi3a8QdVK5JQlS6EnS5X4dQ74zmvXF6RqIGoSDSQRqG/YgenY1Sp8ExHQkEelQ8a5E4ovWtyTaHxJ2LKy+DH4m5XcYCHovyO2PQ1f4Rw64/wB2ceKhO8RI0HKsdSx52O/TNEnLPNtoUdLm0h8dznxAoVZX6fi/0HHcbE+ma25Lq4knjaJwjZQfd2xpIA28PPRsDPXfFcObI4ycUv1ObLKtiHidnCsUr3MiiRgFZlxFJOuCcOo2YjIGrAyR0xWFwbiokijguo2ljUHMafE4CokbPIDkSIudPrRvytPHdO6Jb6VDsbjxUwFkIGI0B3B2LegGPWrXFeMW0JkS1TAUDxJljJQFdmCvjTq3657VEI5K1SIjqqzmXNNmOGXEQjYyx4WQCQASqnTBPY4Pp2r1DnG7n73cCRpU3OMkk6VBwMnqfX616uuKil7uTTTF8hnJYTGFhb26pGrYcnT5gN8KF6/31rPgvpTIsK7JKp1AjUMqCDnsmDjP0og4BwCVZGnd1C+URwxk+EctsSO4x0plpcPJcGdYtEardJKEBbLrsiaOuG0j9f182Mlvw/7JSSBjmK5iSIRRuJGXILKcqh7gEbEn9qDq2uYLa5iC/ek8NpcuE28q5xuo+EegNYRr1sEFGOx0QVI8aeTtTDTlrYoUnf6V5TtTSaXsKBjxXojuRXhTTsc0gJwaRq8prxoAdH2qTFQxn/WpyKYETx537ir/ACpxI2t1FNvpB0yAd432YfTY/SquKbo3pNWqBOnZ1t743IDL8BGRjbb+9q57zxOWuNHaNQg9s+Zv1JFF/IdwHtwD+RiNvTqRXP8AiMviSSSH8zMfpnb9q8/pMenJL4O/qsl418lNI6kFLXq9E88jXZiPXcU+m3I6N6GpBSGI/UH1GPqKik239P4qR+n1pjLn+KAPS7qR7V0afi3iojeEqRxxwzxpHjHgIAGRgu6k4J9dzXOVPl+n70RcEeX7m4gOlxJiTChmdcDAJA1FcZBHtXP1MU4q/JllSa3L78xPeO80sjKjHLRI5TCjZdOkjXgYG/pV6OeBQG8TxCfyAZk2ODq/w49cHqPSqF/wdoQ8pjEkCSeE2jKjplZI3PTuMH2G9VH1OqXcAkeHUIpQQA6uPhbykjJXb3wPWsaUt1wZVe6JOfOERRNFLaxhUIBYxkgK2dwQSSK9Vme9t3jkX70sYUEqWSR/xNhpZVUkE7jpS1rj1VTLi21ugvkjsLoRh7h4Y4ySQv4WZegwVGRp6dR8qh4TxThYvmitbm4zKp8UlsQySJvrLtuDgEZGBvvTr7lvhZQTxyIuoa5ZTO8ryZyWJTONRJz5VG9AdvHaiWW4ZCiIPwogMF1wfMz5yrk6e3Rmz0rjjhjUotuuCYramQc/34mvZSGDKmI1KnKkKMkg99yf0oapzmmV6eOChBRXY3WyodSCvClxVjGMaeajfrTzQA7NIaQGvUgJImpxNRxnepDQMWM71YHSqy1PGdqYDqUUma9QBucrcaFvFcqVclh5CuCAxGkFs7gfKsNtsCpLfiLxCVEwFmTRJnO65yMEHY5+dVw2T2qIwUW35HKTdLwOJp1JS1ZIrLkEe1RQtkCp1qvD0PsT/NAD27/KvCl/0pqUDIyeo9z/AJGt/k/jslnLJJFGHbSCMkqE05DOcdQFYg/OsBuvyq9wOUJOhZ/DU5Vn069KsCN0/MOgI96jIriyZcGx/tR1aWOWNZDKDlWV205yVaNQcY32O+1WOVZ2thNbPh4p4dRBypV1I0SJ77bf9NbPFeAvaILqNvKPKFLBSD1CLG+SOoOMnaqXNqpFaRFnVrwKkIZdlEWS2kKNmJJJ1H9BmuGM7SiuGYQbMjhQR1uLUaSspBjcsF0TIfiOeqnByK9WhylwyOGIzzhT+LGAD0UK+p3377ftSUpZ5Qk1Abk1waB4iDb6EhRctiSUKCx6eUY6AUJ8wKqKNI3dzn10qAN/qentRnxExQwKzTIWDKiRqMuQD5pcdAMeYfOhDnjj4vrgSqipGiKiALpOBk5b1OSf2o6WEpSUnwRhUm7YOk0lIKcRXpHUexS4pBSk0gI3pzGmMd6c5pgIKcDTaUUALmps1AakjO1AEgNSoevzqBTUiHc0DJhS0gpwoEQf8xf79akK4JpjDzrUz9aAG16lNJQAqtUMR3b5mlkbG9RW7UAWQevypiHang7Gq7Hyn9KBiIe9SZNRRVIDQI7zwmwik4RHg+O7AyxhvM4dhjA9QDkVzC9sBGzS3YLuhVHiYAmMFdRPXGr27Vt8g8wTNHBaIw8srAoANTQsrNlXPw6WGK1eYuXkmmWGCJULZmAckGV18snnbzMNwST1zXnS1Qk2+Pg5ns6AjjPEU+7tGspKu6sEB3IAwSe4z3r1XOCRWguJXvtYJZY00DMajIDM7DcBe/tXqtZPT2SbNFHYuX/D1vFVbeSPxIZPhkZU1I/5NRIAbOxUnIx6GgPiGfFfOxDEEDsRsRn0q9YM4/4Shiztk9vKScj+aypT5ifU5/WtsGPRt2KghtPBplOroZYppGNezSMaAI+9OpgO9ONADlrxFIDTqAG06I0jGkFAFgDelB830pKQ/EPlSAsinCmLTqYDW+JfrTz1qInzj2zT9WTtQA80hFeNKKAKt5tio4TUl/0FQwmgC2xwmfU1VnJGB9asS/CB9apznf8AShDJoztT6jTpUgoEXuG8Smt2MlvIY5NJUMuM6TjIBPToN6N+Q+LzPNL4zB9UPhC6c6zC7HWrNqbp5T5Riudg0ZfZzFbySXMNy+YDEHKZ0s7q2QQR0KjPzBrHMvaZ5NlZpcC5JkuGuGilK29vnRqKztcPgFQQuF8Nuv1HuR6inlGzNm9zFFrlEiJ4UOqMSkjdj5mAwAQM/KvVyy1ypxOaWWf+IB8X4fw8JmzM4R0LYbzLnfGSoyDtuDigU0fwSvHbT64mXTG5JJXq5JGwO3XGOtAGOlbdLJy1X5OnEthaXFItOrqND2ajY081G1ADR1p+KYopwoAWlFJS0AIa9Xq9QBNEdqST4h8qbAd6WY7j++9ICypp4NRJTxTAaw8w9wal7/36VEx861I9ADjXhXhXjQBXv/hHzqCHtU9+dh86gtuooGWH3JHoKpNuTVlXyTVVfWgROlSkj0qBXp4NAEi0W3HMEr8Pht1ViAgj8oOnyufM7HdiVCrjoAMbUI6T611H7Opo5+HvbTApplk0TRldUeoIwLjOdOWO52OCO1YdQ6im/JnkdLcD+EKUlUFisyOCodsKTt5NXbUNvrXq2Ty/rnNvFLDcTuVVpZAFgQqdX4UgLN5gME4yc4r1Y/lumYNKW5PzlwC4trIvK6hC48ullYk7Bd9mx1JFc3ajz7QLh3B1uzYZcaiTj9aA2rXpq0bHRiXtPKaeoqMU4Guhmg5sVGsZdlUZJYhRjc5JxsPWnnpU3Cf/AHiH/wCrH/8AsKQnwO4xbeHPKmCNLlcEYO3qOxqmK1+az/vU3/V//K1kCiLuKYou0mLXq9XqYz1er1eoA8p3qSbtURqSToP79KAJ0NPqKOpFoAbIfMvzqd+tV5PiWppKAFXrTs0w9ac1AEF+PKPnVeA1Yvvh+v8ArVWPoaAHxVDIdz86mjqCX4jQBKm9PDAVDHU1v0oAcjiuhfZXwJL771A7MmBG4dQrYJJGgqwI3xn6Vz5K6N9m15Illc6JHX/eIfhYr1XB6HvgfpWWWtO5nk/EPeBcC8/xr91gV0kJiRC7r6OPyDByduleoe+2m4dLZFR2VX0B1UlQwO5DAbHJ33r1Y48UNPBjHGpKz//Z", 
#         "brokerage": "SnapHomz",
#         "logo_url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZQAAAB9CAMAAACyJ2VsAAAAkFBMVEX///8jHyAAAADf398gHB0cFxgGAAD09PQaFRaLiorp6elSUFG0s7PCwcESDA4eGRoOBQiFg4QMAQW6ubqYl5ejoqJFQkNtbGxiYGDLy8ssKCkXERP5+fkzMDHb29vu7u6mpaVGQ0R4dnfJyMisq6tcWloyLzCJiIhOTEx1dHQ9OjuTkpNnZWVeXF3U09QoJCVArH/JAAAMy0lEQVR4nO1ch3biOhCFcaW5gKmml4QW9v//7lkzki0LY0IC4YXonrMbkI0s6WqqBioVDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDY0M49M6PPZG1epoPwjnQ+fZ49EwogWA7bm+mcB3vTbA/nB69qj+MsbzCQR+VYHvQTXS8vIcODWwzxghmAGEs2eP7y8iAq+YEYIHtWeP8M/hNLLLKGEI4tazR/m3UIMLiiunxGD57HH+IYwXV8WEC8tEW5YfQt1yP8dJtWrB9Nmj/RswPqO6MhWmg5YfQB3Mz3OiWfkRON4NckKs1J895pfH/tP2RMA3x88e9ItjF9zKSbUab5496tdGB27npFqF7rPH/cpwbjPyGSvarDwOu9J012W4jWeP/HUx/ZLyQlFZPXvsL4vGzZ6XgL9/9thfFV8XFC0qD0M//jopn7Uq4+mq2Wy2dMbsk3A+Lyim66kEfsYBM6IeANi2nfy/nT/8RNmwRwnizqOf80ispXy9307Wjf3zCnxkF+LjYaewEkTX+jc28oG/ZT/86NIAVu0Bv5qUrZUuGPS6U5Y7ma3e27ZCiw9HloJsKXLlT650XwPVjWj7j9ViBg7xV5OSaS/YyonfOeRkwhvRSqqkXNNfHwXK0Xyse/ACpKSrDPP8hXFD0mv2gLeu1EW2m2W993kfLrMnkNZkPPSM7AVIqfGFKti9u5SVoC/aTiopcdmBPc+pmbBpGo4zG4Zcl5nxI6bC8QKkNMikpHMYrrvrIX+94RrMXdD7+mH7pnoApfGjj3f7ZqoXnQ8iOggfMhnEC5AS4Lp5fL/XEtc1sKHN87+uSRud3NgQAuvcK4PLfZNqNG25zKJPkgmP84x/PykOXzc8sHJE1ZcJJBu0qrDGNxdqXUosfYgEtOe5xolf0HhP/H5SaAY82njLvFdviy17n4WM+HJ7IZVccli/8AtYI6Kt7YMm9AqkDGkGqGAiWRQAvSoWWXoH9qp7KfAv8W9Ns0hTUWBaovW+id9PCrq4fg9f5+JFMuB1EKJw8RysZPZk58HIt/YB/eOHHZD9flJQmXjoCw3zskDSk2xrYPbmLD5JURKo9FB9qU5z87BuTcn2r6NutxthB7PuRxVgEirK0Oj29zFAtfEuCeSYfawboZNoHBom2G+7jAOZlNP7IoZ4G6kVndNoMGpDMDl2pR3jULc4gk7/DeBtOUwvdnbYIIbXOkRnONyryBpJCdDZmucNOQlIYhbsgous/D7BFVKW5FLD4dINCwiCADbJMi+hzVw9P4aGpO1Wi6SZyZtpeeClJQEO+1jASgSMBnmEZgyuoCUj5bQHL/m0aQX5IXQmELCnmaYbwD5dyjp1m7g1nYRJ6vWDSnY6rmgYUEMN780D7uXnIyk2uldRvqIFcLANy8TsVretcBKdTlOcfgkpIltgT5rFHjAGSe6gYniZFxF76bbugyU90oQJ74VcxsRvb0qJtbTuPCUlkmo+4Zg+1NnmakF92PBaqbrYZMtMV3tvNJCsYYT3HgrcHu8HSfnH/qr1LihHzhVSKv/47H0b9uF6eGZGiJTjLLdK7hu/usWNYAYs7483uC6xwklZKzqVs8JJWeVdk1RW6mcZ0tid8StISucgf9BL2NzIasLDjNPjSSGPuKmoL8xPJeoLsgFLV9nyTK+RIiVl/BiPU947snpHUqz+1sLkmDgvAHLQQxyPm8hkfdqkICluSKTEh0Sj+LZ00EB2hEiJ35M/iTWyBQXcs3D4BjDZCQVFzlUrHmdzjEPAXgPR6TRSGth+rIEE7xGkxJjaUo6FyWdN5k3e0ya3vywMLtftK6Qk3eerYRPTAPtuqssox2P5JjTWrdaBH6GZXrZE7pbrFtq+ZOh4ZjsxJtBbT41hFNOymHZGSjWuuhB2Wk2herx37GdB82iP5ifj1P1H2oHIrosP2vv1KblGo/E3Hm8w6aMuW61pJ0OLi439fk9SaBUq/2Svl4iaAerubKqCsVO6puVpYmOfsws4yzaI0fPEm2lzL2fAczDsLWpT00trY/HchzZjetzAcw1pNtqeSyP1uMswpS1umuxNky6mJ20hf890tdAG4iJP/flpw5ZYUUMsp4oPcO9WRcITKbgoa3ndST5Y8MhTjvJV8jNSw1j+hAbYsRLkBC55oiIbmmby9yhY6A1uIHb9duY14QkpRVSCFMgefcQFxCM3TgoPviqpCkAff4QjsbPTzzBIPygkJU2JU+ovaxhDUeA1HpG8j+5WW02kuHRc0shMPdfrmKjiMXs3dUGAbqeKi2ukJOLW3P3Db+Vn1Pg0MSJF0sUUK2Fk0w13m0U7c/1JptH34aS4A+khfL3qKSnSmQ0NlO08MnK541LSD+zuukQegrs+WQPpKSWH0aP94N3v222t3AwG3AS4nBPyuXzuDg0tcE3TF18Q5sHmdVIYxqfm4ehC6vn4mFAjUuTgnvZIv6CH1RkpuaMyWi82GCLFX2TXaBpMRWV3paAaBebrEClWVrdOFFpZxc6wIFmwwS7v+s0QTopY91YP3YkNTdfhiZdAxOTNoxnva9yN4d7I50ghzDoDQYvNVBSSwhOeBNRfZ6Q4q+iIiTSZFDISAkSFV0tfSRUd05QUvgvkqIk6cz8EKdIHZ2pDQQaHnwTe9TtUIr7zhCqYnYZToRx7qTtZUF8/4Qb8FlIS1LmOxOUll1iuHVuckWKsdyOgCDxPikJd2macmTojJQWdZzNf7IFmmjF8ZiNnasM5KTUutHetOkiP6O3j2TUpWX+WKXH2oq7iRlKETUalJSL6DL08Ka1dzN0E31JJ8fK1ShN2l7spWrmMFGIuP9UNSc+XSJlzTm5dg3Jk1SnBIq8VpyO5nAUGuURJy04d3RJSxvVTp3tW5jXmExleI2UWAmacqm4S1O8HlkJKkBdf/CSzJCWkjItE7Oh+mRRhka8Wv90GqWTIglrmQNR3StgXwyG9OmxIifzLpLD8CLTPD04+XLFxS0mZU6ScROWbaDgmI5uTlLz0PkFSeMLibolIgVwdlweN7sqoG6uoB+cFxh5so86qM98FuezRZVIoCQBDtT2MP0MKaWsX+lxdn3lf8S7XK7X1y0lpoybMR3noE5vW7aQYtDXtIl/xW1CK6yzc3QU/LMWv2snWVyLBy6SQm6+sXSXVF9NSUmgXeo1UPM9IoUypgOp9FZNC5aAgh3nca9jcTAr/QrV3/69+nlU83ozLpAjpVk4eK7x5XErKgDEnn+R37Koap8gd0w7I4pRiUqjKDeTTKMrDMl14Gyk8kI97lbvjkaRU3nArqeXGB1w+tjXLSEnXUQDD8hwpsaw31Ii+mJThWWDJB8nijNtIWaASvmNyJcNDSeHZv7gnD1x4kWy9L5NC6y7F7LRiOVJkzvpq7quYFFE2kDluNRQUVIU3kfKBMufHj6hfeygpIvp02yKbWzlt6IEWSv01UrK+x7ShyY5kWWKx8kue8plXrpDC06pp4fRBCjRuIYUCefOOCS8JjyVlxl1n04Z+t7nuLquimJhSRdfUlxnzSZ+qLvke6MsJ9ZW83bTqM2NePT9PuUCKSETAomnMjOaEkiRWWrrzSVL4QawXnYYSVncSm8eSkth64aq5gW0HwnEzuZ9cQgrpIxNqq+Gq2wPT7XFW/i2ES1wLmMvMYqGCk8dLpIgfBsIjS/5jmXyL3ECKOKX1IAfVpfkiLpcOfRblBVZTr+gwO+DpuxJSxDmoRx56POGJAPY1S3FG38wPPn9Gf4GUZJ+o/r749bIvkKIsxZ0yxd/5ajAfSXl+dNxX4lDTg6Uw/GXBYySNzITFWJSGW42smqUrLbAJO2Xl1LXkboExylUdmjDha/m/IaXyfVKuKdJpH4AOuEwrboMdZkPfBq7rtj+km/dtz/OoHmjNY1gzUVFztkQ2sustMlIqpwllx9g9Yu0MSDp186R4rNfUV4t4Tg0LuezUE6vTbalTkpCCDRkpU2pISMEXKu5GyuDLv2xAsBbXnzFu1TYjG+zqdtfNyVV4ZJBTloeQYY6vnWiPtSJ9vr6zI3vbaEqkJJFH+MaMw0e2cvUN63QgJdPrS9bpUnp0ZzlCI/C2lCKhGd4WZmkhR22gjsJT5RTWCnC3H23+rqW/c9ZaheOM82/xf4kUfP+lAM5x/r+/R95Tq01ugj96wpBVUl4PxrdE5Sk/Jfn6pHxLgUlW8QfxB0hJWPmisbcebFAu4S+QUqk3QC2Xu47Em+zdKYK9FX+ClMTfX1pwI9zd2ZHiT+GPkJLAMW7CM93Jv0PKL4Im5X8ITcr/EA5ZtTtXW2l8DzOE/ll3DQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ2NS/gPUsLKT+AIpaYAAAAASUVORK5CYII=", 
#         "zip_codes": ["90210"]
#     }
    
#     sample_market = {
#         "city": "Beverly Hills",
#         "median_price": 3500000,
#         "days_on_market": 24,
#         "list_to_sale_ratio": 98.5,
#         "new_listings": 12,
#         "inventory_months": 3.2
#     }
    
#     sample_llm = "The Beverly Hills housing market remains highly competitive with a strong median price of $3.5M. Homes are selling quickly in just 24 days on average. With low inventory levels, it continues to be a great time for sellers to list their property."
    
#     generate_pdf_with_jinja(sample_agent, sample_market, sample_llm)